import type { MedicalHistory, NutritionScenario, Recipe, RecoveryAction } from "./types";

export const defaultProfileOptions = {
  scenarios: [
    ["pregnancy", "孕期营养餐"],
    ["postpartum", "月子餐"],
    ["lactation", "泌乳期营养餐"],
    ["senior", "中老年营养餐"],
    ["babyFood", "宝宝辅食餐"],
  ] as Array<[NutritionScenario, string]>,
  restrictions: [
    ["noPork", "不吃猪肉"],
    ["noBeefLamb", "不吃牛羊"],
    ["vegetarian", "素食"],
    ["noSeafood", "不吃海鲜"],
    ["noEgg", "鸡蛋过敏/不吃蛋"],
    ["noMilk", "不吃奶制品"],
    ["noSoy", "不吃大豆"],
    ["noPeanut", "不吃花生"],
  ],
  medicalHistory: [
    ["gestationalDiabetes", "妊娠糖尿病/血糖管理"],
    ["diabetes", "糖尿病/血糖偏高"],
    ["hypertension", "高血压/水肿"],
    ["hyperlipidemia", "血脂偏高"],
    ["goutHighUricAcid", "高尿酸/痛风"],
    ["kidneyDisease", "肾功能异常"],
    ["osteoporosis", "骨质疏松/骨量低"],
    ["dysphagia", "咀嚼/吞咽困难"],
    ["anemia", "贫血/铁储备低"],
    ["constipation", "便秘"],
    ["thyroid", "甲状腺问题"],
    ["pluggedDuctRisk", "堵奶/乳腺胀痛风险"],
    ["lactoseIntolerance", "乳糖不耐受"],
  ],
  goals: [
    ["weightControl", "控制体重"],
    ["lactation", "促进泌乳"],
    ["iron", "补铁"],
    ["calcium", "补钙"],
    ["lightTaste", "清淡少盐"],
    ["constipationRelief", "改善便秘"],
    ["woundHealing", "伤口恢复"],
    ["bloodSugarStable", "稳定血糖"],
    ["lowSaltLowFat", "低盐低脂"],
    ["proteinMuscle", "维持肌肉"],
    ["boneHealth", "骨骼健康"],
    ["softEasyDigest", "软烂易消化"],
    ["bowelRegular", "规律排便"],
  ],
} as const;

export const phaseLabels = [
  { min: 1, max: 3, label: "第1-3天 清淡易消化" },
  { min: 4, max: 7, label: "第4-7天 增加蛋白与铁" },
  { min: 8, max: 14, label: "第8-14天 稳定泌乳" },
  { min: 15, max: 28, label: "第15-28天 控重与恢复并重" },
  { min: 29, max: 42, label: "第29-42天 长期哺乳期过渡" },
];

export const fruitPool = [
  "苹果150g，去皮蒸温或常温切块",
  "猕猴桃1个，常温食用，便秘者优先",
  "橙子150g，常温食用，补充维生素C帮助铁吸收",
  "香蕉半根到1根，血糖管理者改半根并随正餐吃",
  "蓝莓80g配无糖酸奶，乳糖不耐者改无糖豆乳",
  "雪梨150g，蒸温后食用，咽干者可选",
  "火龙果150g，便秘者可选，腹泻者避开",
  "草莓120g，清洗后常温食用，适合做下午加餐",
  "柚子100g，随正餐或加餐吃，服药者先问医生是否适合",
  "樱桃80g，补充多酚，血糖管理者控制在小份量",
  "牛油果40g配全麦吐司半片，适合需要增加饱腹感者",
  "苹果梨混合120g，蒸温后撒少量肉桂粉，不加糖",
];

export const nutritionPrinciples = [
  "每日覆盖谷薯、鱼禽蛋肉、奶豆、蔬菜、水果和少量坚果，不用单一大补。",
  "乳母参考：谷类225-275g、蔬菜400-500g、水果200-400g、鱼禽蛋肉175-225g、奶类300-500g、大豆25g、坚果10g、油25-30g、盐不超过5g。",
  "出奶优先保证足量能量、优质蛋白、液体和规律哺乳，避免酒酿、药膳滥用和油腻浓汤。",
  "孕期、月子期、泌乳期、中老年和宝宝辅食均按少盐少油、优质蛋白、足量蔬菜、食品卫生和个体病史优先原则适配。",
  "崔玉涛健康教育风格参考：清淡、均衡、不过度进补，不把单一食材神化为催乳或恢复神器。",
  "妊娠糖尿病、高血压、贫血、甲状腺疾病等人群需遵医嘱复查，本工具只做饮食教育与保守建议。",
  "食品卫生坚持生熟分开、彻底加热、剩菜冷藏并充分复热，避免生食海鲜、未消毒奶制品和酒精饮品。",
];

export const recipes: Recipe[] = [
  {
    id: "b-rice-millet-egg",
    name: "小米南瓜粥配嫩蒸蛋",
    mealType: "breakfast",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["小米35g", "大米20g", "南瓜80g", "鸡蛋1个", "青菜碎30g"],
    seasonings: ["盐0.5g", "芝麻油2g"],
    steps: ["小米和大米淘洗后加水煮25分钟。", "南瓜切丁同煮至软烂。", "鸡蛋加1.5倍温水打匀，蒸8分钟。", "青菜碎焯熟后拌入粥中。"],
    nutritionTags: ["易消化", "优质蛋白", "β-胡萝卜素"],
    avoidTags: ["noEgg"],
    preferTags: ["woundHealing", "lightTaste"],
    replacements: ["鸡蛋过敏时改嫩豆腐80g或鸡胸肉丝40g。"],
    safetyNote: "鸡蛋蒸至完全凝固，不吃半熟蛋。",
  },
  {
    id: "b-oat-milk-berry",
    name: "燕麦牛奶粥配蓝莓核桃",
    mealType: "breakfast",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["燕麦40g", "低脂牛奶250ml", "蓝莓60g", "核桃仁8g", "奇亚籽3g"],
    seasonings: ["不加糖", "肉桂粉少量可选"],
    steps: ["燕麦加牛奶小火煮6分钟。", "关火焖3分钟至软糯。", "蓝莓洗净沥干，核桃掰碎。", "温热后加入蓝莓和核桃。"],
    nutritionTags: ["钙", "膳食纤维", "控重"],
    avoidTags: ["noMilk", "lactoseIntolerance", "noPeanut"],
    preferTags: ["calcium", "constipationRelief", "weightControl"],
    replacements: ["乳糖不耐者改无糖豆乳250ml；坚果过敏者去掉核桃。"],
    safetyNote: "奶类开封后冷藏，避免久放。",
  },
  {
    id: "b-chicken-noodle",
    name: "鸡丝青菜软汤面",
    mealType: "breakfast",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["细面60g", "鸡胸肉50g", "小白菜80g", "胡萝卜30g", "姜片2片"],
    seasonings: ["盐1g", "低盐酱油3ml"],
    steps: ["鸡胸肉煮熟撕丝。", "面条煮至软烂。", "小白菜和胡萝卜烫熟。", "用鸡汤撇油后煮面，最后加鸡丝和蔬菜。"],
    nutritionTags: ["优质蛋白", "补液", "清淡"],
    avoidTags: [],
    preferTags: ["lactation", "woundHealing"],
    replacements: ["不吃禽肉者改豆腐100g或瘦牛肉40g。"],
    safetyNote: "鸡汤需撇去浮油，不用隔夜常温汤。",
  },
  {
    id: "b-redbean-rice",
    name: "红豆糙米软饭配香菇青菜",
    mealType: "breakfast",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["糙米40g", "大米30g", "红豆20g", "香菇30g", "油菜100g"],
    seasonings: ["盐1g", "菜籽油5g"],
    steps: ["红豆提前浸泡并煮软。", "糙米和大米同煮成软饭。", "香菇切片和油菜快炒至熟。", "把红豆拌入软饭搭配蔬菜。"],
    nutritionTags: ["全谷杂豆", "膳食纤维", "控糖友好"],
    avoidTags: [],
    preferTags: ["gestationalDiabetes", "constipationRelief", "weightControl"],
    replacements: ["胀气明显时红豆减半，改山药80g。"],
    safetyNote: "杂豆需煮透，避免夹生引起胃肠不适。",
  },
  {
    id: "b-shrimp-wonton",
    name: "虾仁青菜小馄饨",
    mealType: "breakfast",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["馄饨皮50g", "虾仁60g", "鸡蛋半个", "小白菜90g", "紫菜1g"],
    seasonings: ["盐1g", "白胡椒少量", "芝麻油2g"],
    steps: ["虾仁剁泥后与鸡蛋拌匀。", "包成小馄饨。", "水开后煮至浮起再煮2分钟。", "加入小白菜和紫菜。"],
    nutritionTags: ["优质蛋白", "碘", "低脂"],
    avoidTags: ["noSeafood", "noEgg"],
    preferTags: ["lactation", "weightControl"],
    replacements: ["海鲜过敏时改鸡肉馄饨；鸡蛋过敏时去蛋加少量山药泥。"],
    safetyNote: "虾仁必须煮熟，避免生食或半熟。",
  },
  {
    id: "b-tofu-congee",
    name: "山药豆腐瘦肉粥",
    mealType: "breakfast",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["大米50g", "山药80g", "北豆腐80g", "瘦猪肉35g", "生菜50g"],
    seasonings: ["盐1g", "姜丝2g"],
    steps: ["大米煮成绵粥。", "山药切小块同煮。", "瘦肉剁末焯水后加入。", "豆腐切丁煮透，最后放生菜。"],
    nutritionTags: ["蛋白质", "钙", "易消化"],
    avoidTags: ["noPork", "noSoy"],
    preferTags: ["calcium", "woundHealing"],
    replacements: ["不吃猪肉改鸡腿肉40g；不吃豆制品改鸡蛋1个。"],
    safetyNote: "山药去皮时注意手部防痒，豆腐充分加热。",
  },
  {
    id: "l-steamed-cod",
    name: "清蒸鳕鱼配番茄豆腐青菜饭",
    mealType: "lunch",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["鳕鱼100g", "番茄120g", "北豆腐100g", "西兰花120g", "米饭120g"],
    seasonings: ["姜丝3g", "葱花3g", "低盐酱油5ml", "菜籽油6g"],
    steps: ["鳕鱼加姜丝蒸8-10分钟。", "番茄和豆腐煮成清汤。", "西兰花焯熟后少油快炒。", "搭配温热米饭食用。"],
    nutritionTags: ["DHA", "钙", "低脂蛋白"],
    avoidTags: ["noSeafood", "noSoy"],
    preferTags: ["lactation", "calcium", "weightControl"],
    replacements: ["海鲜过敏改清蒸鸡腿肉100g；不吃豆腐改鸡蛋羹1份。"],
    safetyNote: "鱼肉蒸至中心完全变白，选择低汞鱼类。",
  },
  {
    id: "l-chicken-lotus",
    name: "莲藕鸡腿肉焖饭配菠菜",
    mealType: "lunch",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["去皮鸡腿肉110g", "莲藕90g", "胡萝卜50g", "大米80g", "菠菜120g"],
    seasonings: ["姜片3g", "低盐酱油6ml", "盐1g", "菜籽油6g"],
    steps: ["鸡腿肉切块焯水。", "莲藕和胡萝卜切丁。", "食材与大米同焖至熟。", "菠菜焯水后少油拌炒。"],
    nutritionTags: ["优质蛋白", "铁", "维生素C"],
    avoidTags: [],
    preferTags: ["iron", "woundHealing", "anemia"],
    replacements: ["不吃鸡肉者改瘦牛肉90g或豆腐150g。"],
    safetyNote: "禽肉焖熟到无血水，菠菜焯水减少草酸。",
  },
  {
    id: "l-beef-tomato",
    name: "番茄牛肉土豆炖菜配杂粮饭",
    mealType: "lunch",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["瘦牛肉90g", "番茄180g", "土豆80g", "洋葱30g", "杂粮饭120g"],
    seasonings: ["姜片2g", "盐1g", "低盐酱油5ml"],
    steps: ["牛肉切小块焯水。", "番茄炒出汁后加牛肉慢炖。", "加入土豆炖软。", "搭配杂粮饭，血糖管理者土豆减半。"],
    nutritionTags: ["血红素铁", "蛋白质", "控糖替换"],
    avoidTags: ["noBeefLamb"],
    preferTags: ["anemia", "iron"],
    replacements: ["不吃牛肉改瘦猪肉90g或鸡肉100g。"],
    safetyNote: "牛肉充分炖熟，剩余炖菜冷藏并彻底复热。",
  },
  {
    id: "l-pork-liver",
    name: "猪肝瘦肉菠菜汤饭",
    mealType: "lunch",
    phaseMin: 8,
    phaseMax: 28,
    ingredients: ["猪肝40g", "瘦猪肉50g", "菠菜120g", "大米饭120g", "枸杞3g"],
    seasonings: ["姜丝3g", "盐1g", "白胡椒少量"],
    steps: ["猪肝切薄片反复冲洗并焯水。", "瘦肉煮汤后撇沫。", "加入猪肝煮至全熟。", "菠菜焯水后入汤，配米饭。"],
    nutritionTags: ["补铁", "叶酸", "蛋白质"],
    avoidTags: ["noPork", "hypertension"],
    preferTags: ["anemia", "iron"],
    replacements: ["不吃猪肉改牛肉80g加菠菜；高血压者改鸡肉菠菜汤。"],
    safetyNote: "动物肝脏每周1-2次即可，必须彻底煮熟。",
  },
  {
    id: "l-tofu-mushroom",
    name: "香菇豆腐鸡蛋羹配荞麦饭",
    mealType: "lunch",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["北豆腐150g", "鸡蛋1个", "香菇60g", "油麦菜120g", "荞麦饭120g"],
    seasonings: ["盐1g", "低盐酱油4ml", "芝麻油2g"],
    steps: ["鸡蛋加温水打匀。", "豆腐切丁和香菇片放入蛋液。", "蒸12分钟至凝固。", "油麦菜清炒后配荞麦饭。"],
    nutritionTags: ["钙", "植物蛋白", "控糖友好"],
    avoidTags: ["noSoy", "noEgg"],
    preferTags: ["gestationalDiabetes", "calcium", "weightControl"],
    replacements: ["不吃豆制品改鸡肉末80g；不吃蛋改豆腐蒸肉末。"],
    safetyNote: "蛋羹中心凝固后再食用。",
  },
  {
    id: "l-vegetarian-bowl",
    name: "三色豆腐杂粮能量碗",
    mealType: "lunch",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["北豆腐180g", "鹰嘴豆50g", "藜麦饭120g", "西兰花120g", "彩椒60g"],
    seasonings: ["盐1g", "橄榄油6g", "醋5ml", "低盐酱油4ml"],
    steps: ["鹰嘴豆提前煮熟。", "豆腐煎至两面微黄。", "西兰花和彩椒焯熟。", "与藜麦饭组合，少量油醋调味。"],
    nutritionTags: ["素食蛋白", "膳食纤维", "控重"],
    avoidTags: ["noSoy"],
    preferTags: ["vegetarian", "constipationRelief", "weightControl"],
    replacements: ["不吃豆制品时素食版需营养师补充蛋白方案。"],
    safetyNote: "杂豆提前浸泡并煮透。",
  },
  {
    id: "d-salmon-rice",
    name: "三文鱼南瓜饭配芦笋",
    mealType: "dinner",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["三文鱼90g", "南瓜100g", "大米70g", "芦笋120g", "海带芽5g"],
    seasonings: ["柠檬汁3ml", "盐1g", "姜片2g", "菜籽油5g"],
    steps: ["三文鱼加姜片蒸熟。", "南瓜和大米同焖。", "芦笋焯水后少油快炒。", "海带芽煮汤，不额外加盐。"],
    nutritionTags: ["DHA", "碘", "高营养密度"],
    avoidTags: ["noSeafood", "thyroid"],
    preferTags: ["lactation", "weightControl"],
    replacements: ["海鲜过敏改鸡胸肉100g；甲状腺问题者去海带芽并遵医嘱控碘。"],
    safetyNote: "三文鱼必须全熟，避免刺身。",
  },
  {
    id: "d-turkey-veg",
    name: "鸡胸肉山药时蔬盘",
    mealType: "dinner",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["鸡胸肉100g", "山药100g", "胡萝卜60g", "西葫芦120g", "小米饭100g"],
    seasonings: ["姜汁2ml", "盐1g", "低盐酱油4ml", "菜籽油6g"],
    steps: ["鸡胸肉切片用姜汁抓匀。", "山药蒸熟。", "胡萝卜和西葫芦炒熟。", "鸡肉煎焖至全熟，配小米饭。"],
    nutritionTags: ["低脂蛋白", "控重", "伤口恢复"],
    avoidTags: [],
    preferTags: ["weightControl", "woundHealing"],
    replacements: ["不吃鸡肉改鱼肉或豆腐。"],
    safetyNote: "鸡肉中心无粉色再出锅。",
  },
  {
    id: "d-pork-tenderloin",
    name: "里脊肉冬瓜木耳汤配软饭",
    mealType: "dinner",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["猪里脊80g", "冬瓜180g", "黑木耳50g", "大米饭110g", "小白菜80g"],
    seasonings: ["姜片3g", "盐1g", "白胡椒少量"],
    steps: ["里脊切片焯水。", "冬瓜煮软后加入里脊。", "木耳充分泡发洗净后煮透。", "配软饭和小白菜。"],
    nutritionTags: ["清淡", "补液", "低脂"],
    avoidTags: ["noPork"],
    preferTags: ["lightTaste", "hypertension", "woundHealing"],
    replacements: ["不吃猪肉改鸡腿肉90g。"],
    safetyNote: "干木耳泡发后及时烹调，不隔夜浸泡。",
  },
  {
    id: "d-eggplant-chicken",
    name: "番茄茄子鸡肉煲配燕麦饭",
    mealType: "dinner",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["鸡腿肉90g", "番茄160g", "茄子120g", "燕麦饭110g", "香菇40g"],
    seasonings: ["蒜末2g", "盐1g", "低盐酱油5ml", "菜籽油6g"],
    steps: ["茄子切块蒸软减少吸油。", "鸡腿肉焯水。", "番茄炒出汁后加入鸡肉和茄子焖熟。", "搭配燕麦饭。"],
    nutritionTags: ["控油", "优质蛋白", "全谷"],
    avoidTags: [],
    preferTags: ["weightControl", "constipationRelief"],
    replacements: ["不吃鸡肉改瘦肉或豆腐。"],
    safetyNote: "不用油炸茄子，控制总油量。",
  },
  {
    id: "d-shrimp-tofu",
    name: "虾仁豆腐蒸蛋配青菜",
    mealType: "dinner",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["虾仁70g", "嫩豆腐120g", "鸡蛋1个", "青菜150g", "米饭100g"],
    seasonings: ["盐1g", "低盐酱油4ml", "芝麻油2g"],
    steps: ["鸡蛋加温水打匀。", "豆腐和虾仁铺入碗中。", "蒸12分钟至虾仁变色且蛋液凝固。", "青菜焯熟，配米饭。"],
    nutritionTags: ["蛋白质", "钙", "低脂"],
    avoidTags: ["noSeafood", "noSoy", "noEgg"],
    preferTags: ["calcium", "lactation"],
    replacements: ["海鲜过敏改鸡肉末；不吃蛋改清蒸豆腐鸡肉。"],
    safetyNote: "虾仁和鸡蛋都要完全熟透。",
  },
  {
    id: "d-veg-millet",
    name: "菌菇青菜小米豆腐煲",
    mealType: "dinner",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["小米饭100g", "北豆腐150g", "口蘑80g", "油菜150g", "胡萝卜50g"],
    seasonings: ["盐1g", "菜籽油5g", "姜丝2g"],
    steps: ["小米饭提前煮软。", "豆腐切块煮透。", "口蘑和胡萝卜煮熟。", "加入油菜，少油少盐调味。"],
    nutritionTags: ["素食", "钙", "清淡"],
    avoidTags: ["noSoy"],
    preferTags: ["vegetarian", "lightTaste", "calcium"],
    replacements: ["不吃豆制品改鸡蛋或鱼肉；严格素食需补充B12咨询。"],
    safetyNote: "菌菇类必须煮熟。",
  },
  {
    id: "s-crucian-tofu",
    name: "鲫鱼豆腐清汤",
    mealType: "soup",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["鲫鱼120g", "北豆腐100g", "姜片4g", "小葱3g", "清水600ml"],
    seasonings: ["盐1g", "白胡椒少量"],
    steps: ["鲫鱼处理干净后煎至表面定型。", "加热水和姜片煮20分钟。", "撇去浮油后加豆腐。", "出锅少量盐调味。"],
    nutritionTags: ["补液", "优质蛋白", "泌乳支持"],
    avoidTags: ["noSeafood", "noSoy", "pluggedDuctRisk"],
    preferTags: ["lactation"],
    replacements: ["海鲜过敏改鸡丝豆腐汤；堵奶明显时改冬瓜鸡汤并减少脂肪。"],
    safetyNote: "鱼刺仔细剔除，汤不需熬到浓白油厚。",
  },
  {
    id: "s-chicken-corn",
    name: "玉米胡萝卜去皮鸡汤",
    mealType: "soup",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["去皮鸡腿肉90g", "玉米80g", "胡萝卜80g", "姜片3g", "清水600ml"],
    seasonings: ["盐1g"],
    steps: ["鸡腿肉焯水去浮沫。", "加入玉米、胡萝卜和姜片。", "小火煮30分钟。", "冷却片刻撇油后饮用。"],
    nutritionTags: ["补液", "清淡蛋白", "能量"],
    avoidTags: [],
    preferTags: ["lactation", "woundHealing"],
    replacements: ["不吃鸡肉改瘦肉冬瓜汤或豆腐菌菇汤。"],
    safetyNote: "汤面浮油撇去，不喝油汤。",
  },
  {
    id: "s-wintermelon-pork",
    name: "冬瓜海带瘦肉汤",
    mealType: "soup",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["冬瓜200g", "瘦猪肉60g", "海带结20g", "姜片3g", "清水600ml"],
    seasonings: ["盐1g"],
    steps: ["瘦肉焯水。", "冬瓜切片。", "海带充分清洗后同煮。", "煮至冬瓜透明，少盐调味。"],
    nutritionTags: ["补液", "低脂", "碘"],
    avoidTags: ["noPork", "thyroid"],
    preferTags: ["hypertension", "weightControl"],
    replacements: ["不吃猪肉改鸡肉；甲状腺问题者去海带改香菇。"],
    safetyNote: "甲状腺疾病按医生建议控制碘摄入。",
  },
  {
    id: "s-redbean-barley",
    name: "红豆山药汤",
    mealType: "soup",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["红豆25g", "山药80g", "红枣1枚", "清水600ml"],
    seasonings: ["不加糖"],
    steps: ["红豆提前浸泡。", "加水煮至开花。", "加入山药煮软。", "红枣只放1枚提味，不额外加糖。"],
    nutritionTags: ["膳食纤维", "补液", "控糖调整"],
    avoidTags: [],
    preferTags: ["constipationRelief", "weightControl"],
    replacements: ["血糖管理者红枣可不放，红豆减为15g。"],
    safetyNote: "杂豆煮透，腹胀明显者减少用量。",
  },
  {
    id: "s-mushroom-tofu",
    name: "菌菇豆腐青菜汤",
    mealType: "soup",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["嫩豆腐120g", "口蘑80g", "小白菜100g", "姜丝2g", "清水600ml"],
    seasonings: ["盐1g", "芝麻油1g"],
    steps: ["口蘑切片煮透。", "加入豆腐煮5分钟。", "小白菜最后放入。", "少盐和少量芝麻油调味。"],
    nutritionTags: ["清淡", "钙", "补液"],
    avoidTags: ["noSoy"],
    preferTags: ["lightTaste", "calcium", "vegetarian"],
    replacements: ["不吃豆制品改鸡蛋花或鸡丝。"],
    safetyNote: "菌菇彻底加热，不吃未熟菌菇。",
  },
  {
    id: "sn-yogurt-oat",
    name: "无糖酸奶燕麦杯",
    mealType: "snack",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["无糖酸奶180g", "即食燕麦15g", "蓝莓40g"],
    seasonings: ["不加糖"],
    steps: ["酸奶保持冷藏。", "食用前加入燕麦。", "蓝莓洗净沥干后加入。"],
    nutritionTags: ["钙", "益生菌", "膳食纤维"],
    avoidTags: ["noMilk", "lactoseIntolerance"],
    preferTags: ["calcium", "constipationRelief"],
    replacements: ["乳糖不耐改无糖豆乳200ml加燕麦。"],
    safetyNote: "酸奶离开冷藏不超过2小时。",
  },
  {
    id: "sn-egg-sweetpotato",
    name: "蒸红薯配水煮蛋",
    mealType: "snack",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["红薯120g", "鸡蛋1个"],
    seasonings: ["不加盐"],
    steps: ["红薯洗净蒸熟。", "鸡蛋冷水下锅煮10分钟。", "分成下午加餐或夜间轻食。"],
    nutritionTags: ["饱腹", "优质蛋白", "钾"],
    avoidTags: ["noEgg"],
    preferTags: ["weightControl", "lactation"],
    replacements: ["鸡蛋过敏改豆腐干40g或鸡胸肉40g。"],
    safetyNote: "鸡蛋全熟，红薯血糖管理者减半。",
  },
  {
    id: "sn-soymilk-nut",
    name: "无糖豆浆配坚果",
    mealType: "snack",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["无糖豆浆250ml", "巴旦木10g", "全麦馒头半个"],
    seasonings: ["不加糖"],
    steps: ["豆浆煮沸后再小火3分钟。", "坚果称量10g。", "搭配半个全麦馒头避免空腹饥饿。"],
    nutritionTags: ["植物蛋白", "钙", "控重"],
    avoidTags: ["noSoy", "noPeanut"],
    preferTags: ["lactation", "calcium", "weightControl"],
    replacements: ["不吃豆制品改低脂奶；坚果过敏去掉坚果。"],
    safetyNote: "豆浆必须煮透，避免生豆浆。",
  },
  {
    id: "sn-pear-millet",
    name: "蒸梨小米饮",
    mealType: "snack",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["雪梨150g", "小米15g", "清水400ml"],
    seasonings: ["不加冰糖"],
    steps: ["小米煮成稀饮。", "雪梨去核切块蒸10分钟。", "温热搭配食用。"],
    nutritionTags: ["补液", "温和水果", "少糖"],
    avoidTags: [],
    preferTags: ["lightTaste", "lactation"],
    replacements: ["血糖管理者梨减为80g并随正餐吃。"],
    safetyNote: "不加冰糖，避免把水果饮做成甜汤。",
  },
  {
    id: "sn-chicken-toast",
    name: "鸡丝全麦小三明治",
    mealType: "snack",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["全麦吐司1片", "熟鸡胸肉40g", "生菜30g", "番茄40g"],
    seasonings: ["低脂酸奶酱10g", "黑胡椒少量"],
    steps: ["鸡胸肉煮熟撕丝。", "生菜和番茄洗净沥干。", "夹入吐司，少量酸奶酱调味。"],
    nutritionTags: ["蛋白质", "控重", "全谷"],
    avoidTags: ["noMilk"],
    preferTags: ["weightControl", "lactation"],
    replacements: ["不吃奶制品改牛油果泥10g或不加酱。"],
    safetyNote: "熟鸡肉冷藏保存，当天食用。",
  },
  {
    id: "b-black-sesame-yam",
    name: "黑芝麻山药米糊配鸡肉松",
    mealType: "breakfast",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["大米35g", "山药80g", "熟黑芝麻6g", "鸡胸肉松35g", "小白菜60g"],
    seasonings: ["盐0.5g", "不加糖"],
    steps: ["大米和山药煮软后打成细米糊。", "熟黑芝麻研碎后拌入。", "鸡胸肉煮熟撕细后少盐烘干成肉松。", "小白菜焯熟切碎搭配食用。"],
    nutritionTags: ["钙", "易消化", "优质蛋白"],
    avoidTags: [],
    preferTags: ["calcium", "lactation", "woundHealing"],
    replacements: ["不吃鸡肉者改鱼肉松或豆腐碎；血糖管理者山药减半。"],
    safetyNote: "黑芝麻需熟制，肉松当天制作或冷藏保存。",
  },
  {
    id: "b-spinach-egg-roll",
    name: "菠菜鸡蛋软卷配番茄粥",
    mealType: "breakfast",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["鸡蛋1个", "菠菜80g", "面粉35g", "番茄120g", "大米35g"],
    seasonings: ["盐1g", "菜籽油4g"],
    steps: ["大米和番茄煮成软粥。", "菠菜焯水切碎。", "鸡蛋、面粉和菠菜拌成稀糊。", "平底锅少油摊成软卷。"],
    nutritionTags: ["铁", "叶酸", "软食"],
    avoidTags: ["noEgg"],
    preferTags: ["anemia", "iron", "woundHealing"],
    replacements: ["鸡蛋过敏者改豆腐蔬菜饼；不吃面粉者改米粉。"],
    safetyNote: "菠菜先焯水，蛋卷完全熟透。",
  },
  {
    id: "l-shrimp-pea-rice",
    name: "虾仁豌豆滑蛋饭",
    mealType: "lunch",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["虾仁80g", "鸡蛋1个", "豌豆50g", "胡萝卜50g", "米饭120g"],
    seasonings: ["姜末2g", "盐1g", "菜籽油6g"],
    steps: ["虾仁去虾线后焯至变色。", "豌豆和胡萝卜煮熟。", "鸡蛋炒至凝固后加入虾仁和蔬菜。", "搭配米饭，少油完成。"],
    nutritionTags: ["优质蛋白", "低脂", "锌"],
    avoidTags: ["noSeafood", "noEgg"],
    preferTags: ["lactation", "weightControl"],
    replacements: ["海鲜过敏改鸡丁；鸡蛋过敏改嫩豆腐。"],
    safetyNote: "虾仁必须全熟，豌豆煮透。",
  },
  {
    id: "l-pork-pumpkin-quinoa",
    name: "南瓜瘦肉藜麦饭",
    mealType: "lunch",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["瘦猪肉90g", "南瓜100g", "藜麦饭120g", "芥蓝120g", "香菇40g"],
    seasonings: ["姜丝3g", "低盐酱油5ml", "盐1g", "菜籽油6g"],
    steps: ["瘦肉切片焯水后快炒。", "南瓜蒸熟压块。", "芥蓝焯水后与香菇少油炒熟。", "搭配藜麦饭组合成餐盘。"],
    nutritionTags: ["全谷", "优质蛋白", "控重"],
    avoidTags: ["noPork"],
    preferTags: ["weightControl", "constipationRelief"],
    replacements: ["不吃猪肉改鸡胸肉或鱼肉；血糖管理者南瓜减半。"],
    safetyNote: "瘦肉炒熟到无粉色，熟饭当天食用。",
  },
  {
    id: "d-duck-mushroom-rice",
    name: "去皮鸭肉菌菇软饭",
    mealType: "dinner",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["去皮鸭胸肉80g", "口蘑80g", "杏鲍菇60g", "油菜140g", "软米饭110g"],
    seasonings: ["姜片3g", "盐1g", "低盐酱油4ml"],
    steps: ["鸭胸去皮切薄片并焯水。", "菌菇切片煮透。", "鸭肉和菌菇小火焖熟。", "油菜焯熟后搭配软饭。"],
    nutritionTags: ["铁", "蛋白质", "控油"],
    avoidTags: [],
    preferTags: ["anemia", "weightControl"],
    replacements: ["不吃鸭肉改鸡腿肉或瘦牛肉。"],
    safetyNote: "鸭皮脂肪高，建议去皮并撇油。",
  },
  {
    id: "d-cod-millet-pumpkin",
    name: "鳕鱼小米南瓜煲",
    mealType: "dinner",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["鳕鱼90g", "小米50g", "南瓜80g", "西葫芦120g", "姜片2g"],
    seasonings: ["盐1g", "葱花3g"],
    steps: ["小米和南瓜煮成软煲。", "鳕鱼切块加姜片蒸熟。", "西葫芦切片煮熟。", "鱼肉去刺后放入小米煲中。"],
    nutritionTags: ["DHA", "易消化", "低脂"],
    avoidTags: ["noSeafood"],
    preferTags: ["lactation", "lightTaste", "weightControl"],
    replacements: ["海鲜过敏改鸡胸肉或嫩豆腐。"],
    safetyNote: "鱼刺仔细剔除，鱼肉彻底加热。",
  },
  {
    id: "s-tomato-beef-clear",
    name: "番茄牛肉清汤",
    mealType: "soup",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["瘦牛肉70g", "番茄180g", "芹菜30g", "姜片3g", "清水600ml"],
    seasonings: ["盐1g", "白胡椒少量"],
    steps: ["牛肉焯水后切小块。", "番茄煮出汤汁。", "加入牛肉和姜片小火煮25分钟。", "最后放芹菜增香。"],
    nutritionTags: ["补铁", "补液", "低脂"],
    avoidTags: ["noBeefLamb"],
    preferTags: ["anemia", "iron", "lightTaste"],
    replacements: ["不吃牛肉改鸡肉番茄汤。"],
    safetyNote: "汤面浮油撇去，高血压者不额外加酱油。",
  },
  {
    id: "s-loofah-egg",
    name: "丝瓜鸡蛋清汤",
    mealType: "soup",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["丝瓜180g", "鸡蛋1个", "姜丝2g", "清水550ml"],
    seasonings: ["盐1g", "芝麻油1g"],
    steps: ["丝瓜去皮切片。", "清水加姜丝煮开后放丝瓜。", "鸡蛋打散后淋入成蛋花。", "少盐和少量芝麻油调味。"],
    nutritionTags: ["清淡", "补液", "优质蛋白"],
    avoidTags: ["noEgg"],
    preferTags: ["lactation", "lightTaste"],
    replacements: ["鸡蛋过敏改嫩豆腐80g。"],
    safetyNote: "蛋花完全凝固后食用。",
  },
  {
    id: "sn-snow-fungus-pear",
    name: "银耳雪梨低糖羹",
    mealType: "snack",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["干银耳4g", "雪梨100g", "枸杞3g", "清水450ml"],
    seasonings: ["不加糖"],
    steps: ["银耳泡发后去蒂撕小朵。", "加水煮至软糯。", "加入雪梨块再煮8分钟。", "出锅前放枸杞。"],
    nutritionTags: ["甜品", "补液", "少糖"],
    avoidTags: [],
    preferTags: ["lightTaste", "constipationRelief"],
    replacements: ["血糖管理者雪梨减为60g并随正餐吃。"],
    safetyNote: "银耳泡发后当天烹调，不隔夜浸泡。",
  },
  {
    id: "sn-purple-yam-dessert",
    name: "紫薯山药酸奶杯",
    mealType: "snack",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["紫薯70g", "山药70g", "无糖酸奶120g", "蓝莓30g"],
    seasonings: ["不加糖"],
    steps: ["紫薯和山药蒸熟后压成小块。", "放至温热。", "加入无糖酸奶和蓝莓。", "搅拌后作为下午甜品加餐。"],
    nutritionTags: ["甜品", "钙", "膳食纤维"],
    avoidTags: ["noMilk", "lactoseIntolerance"],
    preferTags: ["calcium", "constipationRelief", "weightControl"],
    replacements: ["乳糖不耐改无糖豆乳酸奶；血糖管理者紫薯减半。"],
    safetyNote: "酸奶冷藏保存，取出后尽快食用。",
  },
  {
    id: "sn-pumpkin-milk-pudding",
    name: "南瓜牛奶蒸布丁",
    mealType: "snack",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["南瓜100g", "鸡蛋1个", "低脂牛奶120ml"],
    seasonings: ["不加糖", "肉桂粉少量可选"],
    steps: ["南瓜蒸熟压泥。", "鸡蛋和牛奶打匀后过滤。", "加入南瓜泥拌匀。", "盖盘蒸12-15分钟至凝固。"],
    nutritionTags: ["甜品", "优质蛋白", "钙"],
    avoidTags: ["noEgg", "noMilk", "lactoseIntolerance"],
    preferTags: ["calcium", "woundHealing"],
    replacements: ["乳糖不耐改无糖豆乳；鸡蛋过敏者改山药南瓜泥。"],
    safetyNote: "布丁中心完全凝固，不吃半熟蛋奶制品。",
  },
  {
    id: "sn-red-date-oat-cake",
    name: "红枣燕麦蒸糕",
    mealType: "snack",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["燕麦粉35g", "鸡蛋1个", "红枣1枚", "无糖豆浆60ml"],
    seasonings: ["不加糖"],
    steps: ["红枣去核切碎。", "燕麦粉、鸡蛋和豆浆拌匀。", "加入红枣碎。", "模具蒸15分钟至熟透。"],
    nutritionTags: ["甜品", "全谷", "饱腹"],
    avoidTags: ["noEgg", "noSoy"],
    preferTags: ["weightControl", "constipationRelief"],
    replacements: ["血糖管理者去红枣；不吃蛋改香蕉泥少量但需减少主食。"],
    safetyNote: "红枣只用1枚提味，不额外加糖。",
  },
  {
    id: "b-cui-style-veg-egg-congee",
    name: "崔玉涛理念·青菜鸡肉蛋花粥",
    mealType: "breakfast",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["大米45g", "鸡胸肉45g", "鸡蛋半个", "小白菜80g", "胡萝卜30g"],
    seasonings: ["盐0.8g", "姜丝2g"],
    steps: ["大米煮成软粥。", "鸡胸肉煮熟撕细丝。", "小白菜和胡萝卜焯熟切碎。", "粥滚后淋入蛋液，完全凝固后加入鸡丝和蔬菜。"],
    nutritionTags: ["崔玉涛理念", "清淡", "优质蛋白", "易消化"],
    avoidTags: ["noEgg"],
    preferTags: ["lightTaste", "woundHealing", "lactation"],
    replacements: ["鸡蛋过敏去蛋，增加嫩豆腐80g；不吃鸡肉改鱼肉或瘦肉丝。"],
    safetyNote: "鸡蛋必须完全凝固，鸡肉煮至中心无粉色。",
  },
  {
    id: "b-diabetes-buckwheat-tofu",
    name: "控糖荞麦豆腐早餐碗",
    mealType: "breakfast",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["荞麦面50g", "北豆腐120g", "上海青120g", "香菇50g", "鸡蛋半个"],
    seasonings: ["低盐酱油4ml", "芝麻油1g", "醋3ml"],
    steps: ["荞麦面煮熟后过温水。", "豆腐和香菇煮透。", "上海青焯熟，鸡蛋煮全熟切半。", "少量调味后拌成温热早餐碗。"],
    nutritionTags: ["控糖友好", "膳食纤维", "优质蛋白", "控重"],
    avoidTags: ["noSoy", "noEgg"],
    preferTags: ["gestationalDiabetes", "weightControl", "constipationRelief"],
    replacements: ["不吃豆制品改鸡胸肉60g；鸡蛋过敏去蛋并增加青菜。"],
    safetyNote: "血糖管理者不要额外加甜酱，主食量按医嘱微调。",
  },
  {
    id: "l-cui-style-fish-plate",
    name: "崔玉涛理念·清蒸鱼蔬菜餐盘",
    mealType: "lunch",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["低汞白身鱼100g", "西兰花120g", "番茄120g", "豆腐80g", "米饭100g"],
    seasonings: ["姜丝3g", "葱花3g", "低盐酱油4ml", "菜籽油5g"],
    steps: ["鱼肉加姜丝蒸至完全熟透。", "西兰花焯熟后少油快炒。", "番茄和豆腐煮成清淡配菜。", "搭配米饭，餐盘一半蔬菜、四分之一蛋白、四分之一主食。"],
    nutritionTags: ["崔玉涛理念", "DHA", "低脂", "控糖友好"],
    avoidTags: ["noSeafood", "noSoy"],
    preferTags: ["gestationalDiabetes", "lactation", "weightControl"],
    replacements: ["海鲜过敏改去皮鸡腿肉100g；不吃豆腐改蒸蛋羹。"],
    safetyNote: "鱼肉不做刺身，选择低汞鱼并彻底加热。",
  },
  {
    id: "l-diabetes-chicken-quinoa",
    name: "控糖鸡胸藜麦彩蔬碗",
    mealType: "lunch",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["鸡胸肉100g", "藜麦饭100g", "芦笋100g", "彩椒60g", "口蘑60g"],
    seasonings: ["姜汁2ml", "盐1g", "低盐酱油4ml", "橄榄油5g"],
    steps: ["鸡胸肉切片，用姜汁抓匀后煎熟。", "芦笋、彩椒和口蘑炒至熟透。", "藜麦饭控制在小碗量。", "组合成高蛋白、高蔬菜餐碗。"],
    nutritionTags: ["控糖友好", "高蛋白", "控重", "膳食纤维"],
    avoidTags: [],
    preferTags: ["gestationalDiabetes", "weightControl", "woundHealing"],
    replacements: ["不吃鸡肉改鳕鱼或豆腐；藜麦可换糙米饭100g。"],
    safetyNote: "鸡肉中心熟透，蔬菜当天烹调当天吃。",
  },
  {
    id: "d-cui-style-tofu-veg",
    name: "崔玉涛理念·菌菇豆腐青菜软饭",
    mealType: "dinner",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["北豆腐150g", "香菇60g", "油菜150g", "胡萝卜40g", "软米饭100g"],
    seasonings: ["盐1g", "姜丝2g", "芝麻油1g"],
    steps: ["豆腐切块煮透。", "香菇、胡萝卜和油菜分别洗净切好。", "少油炒香菌菇后加入豆腐和蔬菜。", "搭配软米饭，口味保持清淡。"],
    nutritionTags: ["崔玉涛理念", "清淡", "钙", "控重"],
    avoidTags: ["noSoy"],
    preferTags: ["lightTaste", "calcium", "weightControl", "vegetarian"],
    replacements: ["不吃豆制品改鸡蛋羹或鱼肉；血糖管理者米饭减到80g并加蔬菜。"],
    safetyNote: "菌菇和豆腐都要充分加热，剩菜冷藏并彻底复热。",
  },
  {
    id: "d-diabetes-beef-celery",
    name: "控糖芹菜牛肉杂粮饭",
    mealType: "dinner",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["瘦牛肉80g", "芹菜120g", "木耳50g", "杂粮饭100g", "番茄80g"],
    seasonings: ["姜丝3g", "低盐酱油4ml", "菜籽油5g"],
    steps: ["牛肉切薄片焯水后快炒至全熟。", "芹菜和木耳炒熟。", "番茄切块做配菜增加维生素C。", "搭配小份杂粮饭。"],
    nutritionTags: ["控糖友好", "血红素铁", "低脂", "膳食纤维"],
    avoidTags: ["noBeefLamb"],
    preferTags: ["gestationalDiabetes", "anemia", "iron", "weightControl"],
    replacements: ["不吃牛肉改鸡胸肉或瘦猪肉；芹菜不适可换西兰花。"],
    safetyNote: "牛肉全熟，木耳泡发后当天烹调。",
  },
  {
    id: "s-cui-style-radish-chicken",
    name: "崔玉涛理念·萝卜鸡丝清汤",
    mealType: "soup",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["白萝卜160g", "鸡胸肉60g", "姜片3g", "小葱2g", "清水600ml"],
    seasonings: ["盐1g", "白胡椒少量"],
    steps: ["鸡胸肉煮熟撕丝。", "白萝卜切片煮至透明。", "加入鸡丝和姜片再煮5分钟。", "出锅前少盐调味并撇去浮油。"],
    nutritionTags: ["崔玉涛理念", "补液", "低脂", "清淡"],
    avoidTags: [],
    preferTags: ["lightTaste", "lactation", "pluggedDuctRisk"],
    replacements: ["不吃鸡肉改鱼片或嫩豆腐；胀气明显者萝卜减半。"],
    safetyNote: "汤水不代替正餐，鸡肉彻底加热。",
  },
  {
    id: "sn-diabetes-yogurt-berry",
    name: "控糖蓝莓酸奶小甜品",
    mealType: "snack",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["无糖酸奶120g", "蓝莓50g", "即食燕麦8g", "熟芝麻2g"],
    seasonings: ["不加糖"],
    steps: ["无糖酸奶取出后短暂回温。", "蓝莓洗净沥干。", "撒入少量燕麦和熟芝麻。", "作为下午加餐，不与正餐大量主食叠加。"],
    nutritionTags: ["控糖友好", "甜品", "钙", "少糖"],
    avoidTags: ["noMilk", "lactoseIntolerance"],
    preferTags: ["gestationalDiabetes", "calcium", "weightControl"],
    replacements: ["乳糖不耐改无糖豆乳酸奶；蓝莓可换苹果丁50g。"],
    safetyNote: "不加蜂蜜、糖浆或果酱；酸奶冷藏保存。",
  },
  {
    id: "sn-cui-style-apple-oat",
    name: "崔玉涛理念·苹果燕麦蒸盅",
    mealType: "snack",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["苹果80g", "燕麦15g", "鸡蛋半个", "清水80ml"],
    seasonings: ["不加糖", "肉桂粉少量可选"],
    steps: ["苹果去皮切小丁。", "燕麦加水泡软。", "加入半个蛋液拌匀。", "蒸12分钟至完全凝固，温热食用。"],
    nutritionTags: ["崔玉涛理念", "甜品", "少糖", "膳食纤维"],
    avoidTags: ["noEgg"],
    preferTags: ["lightTaste", "constipationRelief", "weightControl"],
    replacements: ["鸡蛋过敏去蛋，改山药泥40g；血糖管理者苹果减到50g。"],
    safetyNote: "不额外加糖，蛋液完全凝固后食用。",
  },
  {
    id: "b-iron-beef-millet",
    name: "补铁牛肉小米青菜粥",
    mealType: "breakfast",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["小米40g", "瘦牛肉45g", "油菜80g", "胡萝卜30g", "姜丝2g"],
    seasonings: ["盐0.8g", "低盐酱油2ml"],
    steps: ["小米洗净煮成软粥。", "牛肉剁末焯水去浮沫。", "油菜和胡萝卜焯熟切碎。", "牛肉末入粥煮透，最后加入蔬菜。"],
    nutritionTags: ["早餐优化", "血红素铁", "优质蛋白", "易消化"],
    avoidTags: ["noBeefLamb"],
    preferTags: ["anemia", "iron", "woundHealing"],
    replacements: ["不吃牛肉改瘦猪肉或鸡肉；贫血严重者需遵医嘱补铁。"],
    safetyNote: "牛肉必须完全煮熟，粥不隔夜常温放置。",
  },
  {
    id: "b-cesarean-lotus-chicken-congee",
    name: "剖宫产友好莲藕鸡丝粥",
    mealType: "breakfast",
    phaseMin: 1,
    phaseMax: 14,
    ingredients: ["大米45g", "去皮鸡腿肉50g", "莲藕60g", "小白菜60g", "姜片2片"],
    seasonings: ["盐0.8g"],
    steps: ["大米煮成绵粥。", "鸡腿肉煮熟后撕细丝。", "莲藕切小丁煮软。", "加入小白菜碎，少盐调味。"],
    nutritionTags: ["早餐优化", "剖宫产友好", "易消化", "优质蛋白"],
    avoidTags: [],
    preferTags: ["cesarean", "woundHealing", "lightTaste"],
    replacements: ["腹胀明显时莲藕减半，改胡萝卜或冬瓜丁。"],
    safetyNote: "早期少量多餐，伤口疼痛或腹胀明显时先按医生建议进食。",
  },
  {
    id: "b-diabetes-egg-veggie-oat",
    name: "控糖蔬菜蛋燕麦杯",
    mealType: "breakfast",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["燕麦30g", "鸡蛋1个", "西兰花80g", "口蘑50g", "无糖豆浆120ml"],
    seasonings: ["盐0.8g", "黑胡椒少量"],
    steps: ["燕麦用无糖豆浆泡软。", "西兰花和口蘑焯熟切碎。", "加入蛋液拌匀后装碗。", "蒸12-15分钟至完全凝固。"],
    nutritionTags: ["早餐优化", "控糖友好", "膳食纤维", "优质蛋白"],
    avoidTags: ["noEgg", "noSoy"],
    preferTags: ["gestationalDiabetes", "weightControl", "constipationRelief"],
    replacements: ["不吃蛋改嫩豆腐100g；不吃豆制品改低脂牛奶或清水。"],
    safetyNote: "不加糖，不搭配甜饮；蛋液完全凝固后食用。",
  },
  {
    id: "b-lactation-fish-rice-noodle",
    name: "泌乳支持鲈鱼米粉汤",
    mealType: "breakfast",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["鲈鱼片80g", "米粉60g", "生菜80g", "番茄80g", "姜片3g"],
    seasonings: ["盐1g", "葱花3g"],
    steps: ["鱼片加姜片蒸熟后去刺。", "米粉煮软。", "番茄煮出清汤后加入生菜。", "放入鱼片和米粉，少盐调味。"],
    nutritionTags: ["早餐优化", "泌乳支持", "DHA", "低脂"],
    avoidTags: ["noSeafood"],
    preferTags: ["lactation", "lightTaste", "weightControl"],
    replacements: ["海鲜过敏改鸡丝米粉汤；控糖者米粉减到45g并加青菜。"],
    safetyNote: "鱼片彻底加热并仔细去刺。",
  },
  {
    id: "sn-iron-orange-yogurt",
    name: "补铁搭配橙香酸奶碗",
    mealType: "snack",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["无糖酸奶120g", "橙子80g", "即食燕麦10g", "南瓜籽5g"],
    seasonings: ["不加糖"],
    steps: ["酸奶取出后短暂回温。", "橙子去膜切小块。", "加入燕麦和南瓜籽。", "作为上午或下午加餐。"],
    nutritionTags: ["加餐优化", "补铁搭配", "钙", "少糖"],
    avoidTags: ["noMilk", "lactoseIntolerance", "noPeanut"],
    preferTags: ["anemia", "iron", "calcium"],
    replacements: ["乳糖不耐改无糖豆乳酸奶；坚果籽类过敏去掉南瓜籽。"],
    safetyNote: "酸奶冷藏保存，不额外加蜂蜜或糖浆。",
  },
  {
    id: "sn-diabetes-tofu-berry",
    name: "控糖豆乳莓果布丁",
    mealType: "snack",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["无糖豆浆160ml", "吉利丁或琼脂少量", "蓝莓40g", "奇亚籽3g"],
    seasonings: ["不加糖"],
    steps: ["无糖豆浆煮开后按说明加入琼脂。", "倒入小碗冷藏凝固。", "食用前加蓝莓和奇亚籽。", "作为小份下午甜品。"],
    nutritionTags: ["加餐优化", "控糖友好", "甜品", "少糖"],
    avoidTags: ["noSoy"],
    preferTags: ["gestationalDiabetes", "weightControl", "constipationRelief"],
    replacements: ["不吃豆制品改无糖酸奶；蓝莓可换草莓60g。"],
    safetyNote: "不使用代糖饮料替代正餐，冷藏后尽快食用。",
  },
  {
    id: "sn-cesarean-protein-custard",
    name: "剖宫产友好鸡肉豆腐蒸杯",
    mealType: "snack",
    phaseMin: 1,
    phaseMax: 21,
    ingredients: ["嫩豆腐90g", "鸡胸肉30g", "鸡蛋半个", "小白菜30g"],
    seasonings: ["盐0.5g", "芝麻油1g"],
    steps: ["鸡胸肉煮熟切碎。", "豆腐压碎，与蛋液和鸡肉碎混合。", "加入小白菜碎。", "蒸10-12分钟至凝固。"],
    nutritionTags: ["加餐优化", "剖宫产友好", "优质蛋白", "易消化"],
    avoidTags: ["noSoy", "noEgg"],
    preferTags: ["cesarean", "woundHealing", "calcium"],
    replacements: ["不吃豆制品改鸡蛋羹；鸡蛋过敏改鸡肉豆腐羹不加蛋。"],
    safetyNote: "蒸至中心完全凝固，早期一次吃小份。",
  },
  {
    id: "sn-warm-fruit-oat-cup",
    name: "温水果燕麦加餐杯",
    mealType: "snack",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["苹果60g", "雪梨60g", "燕麦12g", "无糖酸奶80g"],
    seasonings: ["不加糖", "肉桂粉少量可选"],
    steps: ["苹果和雪梨切丁蒸8分钟。", "燕麦加热水泡软。", "水果放至温热后与燕麦混合。", "能接受冷食者再加少量酸奶。"],
    nutritionTags: ["加餐优化", "水果", "膳食纤维", "少糖"],
    avoidTags: ["noMilk", "lactoseIntolerance"],
    preferTags: ["constipationRelief", "lightTaste", "weightControl"],
    replacements: ["乳糖不耐去酸奶或改无糖豆乳；控糖者水果总量减到80g。"],
    safetyNote: "蒸水果不加冰糖，避免做成甜汤。",
  },
  {
    id: "b-pregnancy-calcium-egg",
    name: "孕期钙铁双补早餐盘",
    mealType: "breakfast",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["全麦馒头半个", "鸡蛋1个", "菠菜80g", "低脂牛奶200ml", "橙子80g"],
    seasonings: ["盐0.8g", "菜籽油4g"],
    steps: ["鸡蛋煮至全熟。", "菠菜焯水后少油快炒。", "全麦馒头蒸热。", "搭配低脂牛奶和小份橙子。"],
    nutritionTags: ["孕期友好", "早餐优化", "钙", "补铁搭配"],
    avoidTags: ["noEgg", "noMilk"],
    preferTags: ["pregnancy", "iron", "calcium", "anemia"],
    replacements: ["乳糖不耐改无乳糖奶；不吃蛋改豆腐100g。"],
    safetyNote: "孕期不吃半熟蛋，奶类选择巴氏杀菌或充分灭菌产品。",
  },
  {
    id: "b-senior-oat-fish",
    name: "中老年燕麦鱼肉青菜粥",
    mealType: "breakfast",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["燕麦25g", "大米25g", "低汞鱼肉60g", "青菜100g", "香菇30g"],
    seasonings: ["盐0.8g", "芝麻油1g"],
    steps: ["燕麦和大米煮成软粥。", "鱼肉蒸熟去刺。", "青菜和香菇煮熟切碎。", "加入鱼肉，少盐调味。"],
    nutritionTags: ["中老年友好", "早餐优化", "低脂", "膳食纤维"],
    avoidTags: ["noSeafood"],
    preferTags: ["senior", "hypertension", "weightControl", "calcium", "proteinMuscle", "boneHealth", "softEasyDigest"],
    replacements: ["海鲜过敏改鸡胸肉；吞咽困难者按医嘱调整质地。"],
    safetyNote: "鱼刺必须剔除干净，中老年人群注意低盐和软烂度。",
  },
  {
    id: "l-pregnancy-salmon-lentil",
    name: "孕期低汞鱼豆蔬菜饭",
    mealType: "lunch",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["熟三文鱼80g", "鹰嘴豆40g", "西兰花120g", "番茄100g", "糙米饭100g"],
    seasonings: ["柠檬汁3ml", "盐1g", "橄榄油5g"],
    steps: ["三文鱼蒸熟或煎熟至中心熟透。", "鹰嘴豆提前煮软。", "西兰花焯熟，番茄切块。", "搭配糙米饭做餐盘。"],
    nutritionTags: ["孕期友好", "DHA", "膳食纤维", "控糖友好"],
    avoidTags: ["noSeafood"],
    preferTags: ["pregnancy", "gestationalDiabetes", "constipationRelief"],
    replacements: ["海鲜过敏改鸡腿肉；血糖管理者糙米饭按医嘱调整。"],
    safetyNote: "孕期鱼类必须全熟，选择低汞鱼，避免生食海鲜。",
  },
  {
    id: "d-senior-tofu-shrimp",
    name: "中老年虾仁豆腐软菜饭",
    mealType: "dinner",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["虾仁60g", "嫩豆腐120g", "冬瓜150g", "小白菜120g", "杂粮软饭90g"],
    seasonings: ["盐0.8g", "姜丝2g", "芝麻油1g"],
    steps: ["虾仁去虾线后煮熟。", "豆腐和冬瓜煮软。", "小白菜切碎煮熟。", "搭配小份杂粮软饭。"],
    nutritionTags: ["中老年友好", "低脂", "钙", "控糖友好"],
    avoidTags: ["noSeafood", "noSoy"],
    preferTags: ["senior", "hypertension", "diabetes", "bloodSugarStable", "calcium", "boneHealth"],
    replacements: ["海鲜过敏改鸡肉末；不吃豆制品改鸡蛋羹。"],
    safetyNote: "虾仁必须全熟，低盐调味，剩菜充分复热。",
  },
  {
    id: "s-lactation-millet-fish",
    name: "泌乳期小米鱼片补液汤",
    mealType: "soup",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["小米15g", "鱼片70g", "丝瓜120g", "姜片3g", "清水650ml"],
    seasonings: ["盐1g", "葱花3g"],
    steps: ["小米先煮成淡汤底。", "丝瓜切片煮软。", "鱼片入汤煮至完全变白。", "少盐调味，不额外加油。"],
    nutritionTags: ["泌乳期友好", "泌乳支持", "补液", "低脂"],
    avoidTags: ["noSeafood"],
    preferTags: ["lactation", "breastfeeding", "mixed", "pluggedDuctRisk"],
    replacements: ["海鲜过敏改鸡丝汤；堵奶风险者继续保持低脂清汤。"],
    safetyNote: "汤水用于补液，不替代正餐和规律排乳。",
  },
  {
    id: "b-lactation-milk-oat-egg",
    name: "泌乳期燕麦奶蛋早餐",
    mealType: "breakfast",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["燕麦35g", "低脂牛奶220ml", "鸡蛋1个", "小白菜80g", "核桃仁5g"],
    seasonings: ["不加糖", "盐0.5g"],
    steps: ["燕麦用牛奶煮软。", "鸡蛋煮至全熟。", "小白菜焯熟少盐调味。", "核桃掰碎撒在燕麦上。"],
    nutritionTags: ["泌乳期友好", "泌乳支持", "早餐优化", "钙"],
    avoidTags: ["noMilk", "noEgg", "noPeanut"],
    preferTags: ["lactation", "breastfeeding", "mixed", "calcium"],
    replacements: ["乳糖不耐改无糖豆乳；鸡蛋过敏改鸡胸肉40g。"],
    safetyNote: "不加糖，不用酒酿；坚果需确认不过敏。",
  },
  {
    id: "l-lactation-chicken-rice",
    name: "泌乳期鸡肉豆腐蔬菜饭",
    mealType: "lunch",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["去皮鸡腿肉100g", "北豆腐100g", "西兰花120g", "胡萝卜50g", "米饭120g"],
    seasonings: ["姜片3g", "盐1g", "低盐酱油4ml"],
    steps: ["鸡腿肉焯水后煮熟。", "豆腐煮透。", "西兰花和胡萝卜焯熟后少油拌炒。", "搭配米饭组成餐盘。"],
    nutritionTags: ["泌乳期友好", "泌乳支持", "优质蛋白", "钙"],
    avoidTags: ["noSoy"],
    preferTags: ["lactation", "breastfeeding", "mixed", "calcium"],
    replacements: ["不吃豆腐改蒸蛋羹；控重者米饭减到100g并增加蔬菜。"],
    safetyNote: "禽肉彻底加热，汤汁撇油。",
  },
  {
    id: "d-lactation-shrimp-noodle",
    name: "泌乳期虾仁青菜软面",
    mealType: "dinner",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["虾仁70g", "细面60g", "油菜120g", "番茄100g", "姜片2g"],
    seasonings: ["盐1g", "芝麻油1g"],
    steps: ["虾仁去虾线后煮熟。", "番茄煮成清汤。", "面条煮软后加入油菜。", "最后加入虾仁少盐调味。"],
    nutritionTags: ["泌乳期友好", "泌乳支持", "低脂", "补液"],
    avoidTags: ["noSeafood"],
    preferTags: ["lactation", "breastfeeding", "mixed"],
    replacements: ["海鲜过敏改鸡丝软面。"],
    safetyNote: "虾仁必须全熟，不使用高盐汤底。",
  },
  {
    id: "sn-lactation-yogurt-fruit",
    name: "泌乳期酸奶水果加餐",
    mealType: "snack",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["无糖酸奶150g", "蓝莓50g", "燕麦10g", "芝麻粉3g"],
    seasonings: ["不加糖"],
    steps: ["酸奶取出后短暂回温。", "蓝莓清洗沥干。", "加入燕麦和芝麻粉。", "作为下午加餐。"],
    nutritionTags: ["泌乳期友好", "泌乳支持", "加餐优化", "钙"],
    avoidTags: ["noMilk", "lactoseIntolerance"],
    preferTags: ["lactation", "breastfeeding", "mixed", "calcium"],
    replacements: ["乳糖不耐改无糖豆乳酸奶。"],
    safetyNote: "酸奶冷藏保存，不加蜂蜜或糖浆。",
  },
  {
    id: "sn-pregnancy-fruit-yogurt",
    name: "孕期莓果酸奶坚果杯",
    mealType: "snack",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["无糖酸奶150g", "草莓80g", "蓝莓40g", "核桃仁6g", "燕麦8g"],
    seasonings: ["不加糖"],
    steps: ["水果清洗沥干。", "酸奶取出后短暂回温。", "加入燕麦和核桃碎。", "作为上午或下午加餐。"],
    nutritionTags: ["孕期友好", "加餐优化", "钙", "少糖"],
    avoidTags: ["noMilk", "lactoseIntolerance", "noPeanut"],
    preferTags: ["pregnancy", "calcium", "constipationRelief"],
    replacements: ["乳糖不耐改无糖豆乳酸奶；坚果过敏去核桃。"],
    safetyNote: "奶制品需来源可靠并冷藏保存，水果洗净后尽快食用。",
  },
  {
    id: "d-pregnancy-beef-spinach",
    name: "孕期番茄牛肉菠菜饭",
    mealType: "dinner",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["瘦牛肉80g", "番茄150g", "菠菜100g", "糙米饭100g", "姜片2g"],
    seasonings: ["盐1g", "低盐酱油4ml"],
    steps: ["牛肉焯水后炖熟。", "番茄煮出汤汁后加入牛肉。", "菠菜焯水后拌入。", "搭配糙米饭。"],
    nutritionTags: ["孕期友好", "血红素铁", "控糖友好", "优质蛋白"],
    avoidTags: ["noBeefLamb"],
    preferTags: ["pregnancy", "anemia", "iron", "gestationalDiabetes"],
    replacements: ["不吃牛肉改鸡肉或鱼肉；血糖管理者糙米饭按医嘱调整。"],
    safetyNote: "牛肉彻底煮熟，菠菜先焯水。",
  },
  {
    id: "s-pregnancy-tofu-veg",
    name: "孕期豆腐菌菇青菜汤",
    mealType: "soup",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["北豆腐100g", "口蘑60g", "小白菜100g", "番茄80g", "清水600ml"],
    seasonings: ["盐1g", "芝麻油1g"],
    steps: ["口蘑煮透。", "豆腐切块煮开。", "加入番茄和小白菜。", "少盐调味。"],
    nutritionTags: ["孕期友好", "钙", "清淡", "补液"],
    avoidTags: ["noSoy"],
    preferTags: ["pregnancy", "calcium", "lightTaste"],
    replacements: ["不吃豆制品改鸡蛋花汤。"],
    safetyNote: "菌菇和豆腐充分加热，孕期不吃未消毒奶制品和生食。",
  },
  {
    id: "l-senior-chicken-barley",
    name: "中老年鸡肉薏米软饭",
    mealType: "lunch",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["鸡胸肉80g", "薏米饭90g", "南瓜60g", "油菜120g", "香菇40g"],
    seasonings: ["盐0.8g", "菜籽油4g"],
    steps: ["鸡胸肉煮熟切碎。", "薏米饭煮软。", "南瓜蒸软。", "油菜和香菇炒熟后切小。"],
    nutritionTags: ["中老年友好", "低脂", "膳食纤维", "优质蛋白"],
    avoidTags: [],
    preferTags: ["senior", "hypertension", "weightControl", "lowSaltLowFat", "proteinMuscle"],
    replacements: ["咀嚼困难者改成粥或软烂小块。"],
    safetyNote: "低盐调味，吞咽困难者需按医嘱调整质地。",
  },
  {
    id: "s-senior-seaweed-egg",
    name: "中老年番茄蛋花青菜汤",
    mealType: "soup",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["番茄120g", "鸡蛋1个", "小白菜100g", "清水600ml"],
    seasonings: ["盐0.8g", "芝麻油1g"],
    steps: ["番茄煮出汤汁。", "加入小白菜煮软。", "鸡蛋打散淋入。", "少盐调味。"],
    nutritionTags: ["中老年友好", "清淡", "补液", "优质蛋白"],
    avoidTags: ["noEgg"],
    preferTags: ["senior", "hypertension", "lightTaste", "lowSaltLowFat", "softEasyDigest"],
    replacements: ["鸡蛋过敏改豆腐或鸡丝。"],
    safetyNote: "低盐，蛋花完全凝固后食用。",
  },
  {
    id: "sn-senior-bean-paste",
    name: "中老年红豆山药小甜盅",
    mealType: "snack",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["红豆20g", "山药70g", "无糖豆浆100ml", "桂花少量"],
    seasonings: ["不加糖"],
    steps: ["红豆提前浸泡并煮软。", "山药蒸熟压泥。", "加入无糖豆浆调成软糊。", "撒少量桂花提香。"],
    nutritionTags: ["中老年友好", "加餐优化", "甜品", "膳食纤维"],
    avoidTags: ["noSoy"],
    preferTags: ["senior", "constipationRelief", "diabetes", "bloodSugarStable", "bowelRegular"],
    replacements: ["血糖管理者红豆减半；不吃豆制品改温水调糊。"],
    safetyNote: "不加糖，不做过甜点心；杂豆需彻底煮软。",
  },
  {
    id: "b-baby-iron-rice-cereal",
    name: "宝宝高铁米粉南瓜泥",
    mealType: "breakfast",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["婴儿高铁米粉15g", "南瓜泥20g", "温开水适量"],
    seasonings: ["不加盐", "不加糖"],
    steps: ["南瓜蒸熟压成细泥。", "高铁米粉按包装说明用温水调成细糊。", "加入少量南瓜泥搅匀。", "首次尝试南瓜时先少量观察。"],
    nutritionTags: ["宝宝辅食", "高铁", "细泥", "不加盐糖"],
    avoidTags: [],
    preferTags: ["babyFood"],
    replacements: ["首次添加辅食优先单一高铁米粉，确认耐受后再加南瓜泥。"],
    safetyNote: "适合已满6月龄且医生/儿保确认可添加辅食的宝宝；1岁内不加盐糖蜂蜜。",
  },
  {
    id: "l-baby-chicken-veg-congee",
    name: "宝宝鸡肉胡萝卜软粥",
    mealType: "lunch",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["大米粥60g", "鸡胸肉泥15g", "胡萝卜泥20g", "青菜泥10g"],
    seasonings: ["不加盐", "不加酱油"],
    steps: ["大米煮成软烂粥。", "鸡胸肉彻底煮熟后打成细泥。", "胡萝卜和青菜蒸熟打泥。", "混合后调到适合宝宝吞咽的稠度。"],
    nutritionTags: ["宝宝辅食", "优质蛋白", "软烂", "铁锌"],
    avoidTags: [],
    preferTags: ["babyFood"],
    replacements: ["初次添加肉类时先从少量肉泥开始，连续观察2-3天。"],
    safetyNote: "鸡肉必须全熟，辅食现做现吃，不喂隔夜常温食物。",
  },
  {
    id: "d-baby-cod-potato",
    name: "宝宝鳕鱼土豆泥",
    mealType: "dinner",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["低汞鳕鱼20g", "土豆40g", "西兰花泥10g"],
    seasonings: ["不加盐", "不加调味酱"],
    steps: ["鳕鱼加姜片蒸熟后去姜并仔细检查鱼刺。", "土豆蒸熟压成泥。", "西兰花蒸熟打泥。", "混合成细腻泥状，少量喂食。"],
    nutritionTags: ["宝宝辅食", "DHA", "细泥", "优质蛋白"],
    avoidTags: ["noSeafood"],
    preferTags: ["babyFood"],
    replacements: ["鱼类未尝试过时先少量单独添加；海鲜过敏风险家庭先咨询儿保医生。"],
    safetyNote: "鱼刺必须完全剔除；宝宝辅食不使用成人汤底和调味料。",
  },
  {
    id: "sn-baby-apple-pear-puree",
    name: "宝宝苹果梨细泥",
    mealType: "snack",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["苹果30g", "梨30g", "温开水少量"],
    seasonings: ["不加糖"],
    steps: ["苹果和梨去皮去核。", "蒸软后打成细泥。", "根据吞咽能力调整稠度。", "首次尝试水果时先单一水果。"],
    nutritionTags: ["宝宝辅食", "水果泥", "不加糖"],
    avoidTags: [],
    preferTags: ["babyFood"],
    replacements: ["腹泻时暂停高果糖水果泥，按儿科医生建议调整。"],
    safetyNote: "水果泥不能替代奶量；1岁内不加蜂蜜。",
  },
  {
    id: "s-baby-tomato-tofu",
    name: "宝宝番茄豆腐小汤羹",
    mealType: "soup",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["番茄30g", "嫩豆腐30g", "清水120ml"],
    seasonings: ["不加盐", "不加鸡精"],
    steps: ["番茄去皮切碎。", "嫩豆腐煮透后压碎。", "清水煮成小汤羹。", "放温后少量喂食。"],
    nutritionTags: ["宝宝辅食", "植物蛋白", "软烂", "不加盐糖"],
    avoidTags: ["noSoy"],
    preferTags: ["babyFood"],
    replacements: ["大豆过敏或未尝试豆制品时不添加豆腐。"],
    safetyNote: "辅食汤羹不替代母乳或配方奶；豆腐需充分加热。",
  },
];

export const recoveryBaseActions: Record<string, RecoveryAction> = {
  breathing: {
    name: "腹式呼吸",
    duration: "5分钟",
    steps: ["仰卧或侧卧，双手放在下肋。", "吸气时肋骨向两侧打开，呼气时轻收下腹。", "全程不憋气，不追求用力收腹。"],
    suitableFor: ["顺产", "剖宫产", "产后早期"],
    avoidWhen: ["头晕", "胸闷", "伤口明显牵拉痛"],
  },
  pelvicFloor: {
    name: "盆底肌温和收缩",
    duration: "8-10次/组，2-3组",
    steps: ["像轻轻忍住排气一样向上收。", "保持2-3秒后完全放松。", "不要夹臀、憋气或用大腿代偿。"],
    suitableFor: ["顺产", "剖宫产", "尿失禁预防"],
    avoidWhen: ["会阴疼痛加重", "盆底痉挛感", "恶露明显增多"],
  },
  anklePump: {
    name: "踝泵",
    duration: "每侧20次",
    steps: ["平躺或坐位，脚尖向上勾。", "再缓慢向下绷脚。", "配合脚踝画圈促进循环。"],
    suitableFor: ["卧床多", "剖宫产早期"],
    avoidWhen: ["小腿单侧红肿热痛"],
  },
  shoulderNeck: {
    name: "肩颈放松",
    duration: "6分钟",
    steps: ["肩膀向后绕环10次。", "下巴微收做颈后侧拉长。", "哺乳后做胸前轻柔打开。"],
    suitableFor: ["哺乳", "抱娃肩颈紧"],
    avoidWhen: ["手臂麻木加重", "眩晕"],
  },
  pelvicTilt: {
    name: "骨盆前后倾",
    duration: "10次/组，2组",
    steps: ["仰卧屈膝或站姿扶墙。", "呼气时轻轻让腰背贴近床面。", "吸气还原，动作幅度小。"],
    suitableFor: ["产后腰背酸", "腹直肌恢复早期"],
    avoidWhen: ["剖宫产伤口牵拉痛", "出血增多"],
  },
  catCow: {
    name: "猫牛式",
    duration: "8-10次",
    steps: ["四点跪位，手在肩下、膝在髋下。", "吸气胸口打开，呼气背部轻柔拱起。", "保持慢速，不塌腰。"],
    suitableFor: ["第8天后恢复良好者"],
    avoidWhen: ["腕痛", "剖宫产伤口不适", "会阴疼痛加重"],
  },
  walk: {
    name: "轻松散步",
    duration: "10-30分钟",
    steps: ["从室内短距离开始。", "能说完整句子的强度即可。", "分2次完成也可以。"],
    suitableFor: ["恢复稳定", "控重", "情绪调节"],
    avoidWhen: ["头晕", "胸痛", "出血增多", "伤口疼痛"],
  },
  lightStrength: {
    name: "坐姿弹力带划船",
    duration: "10次/组，2组",
    steps: ["坐稳，弹力带绕脚或固定点。", "呼气时手肘向后拉。", "吸气慢慢还原，肩膀放松。"],
    suitableFor: ["第29天后恢复良好者", "肩背无痛"],
    avoidWhen: ["剖宫产伤口痛", "盆底下坠感", "尿失禁加重"],
  },
};

export const conditionNotes: Record<MedicalHistory, string> = {
  gestationalDiabetes: "血糖管理：主食分配到三餐两加餐，水果随正餐或加餐少量吃，避免甜汤、果汁和大量精制点心。",
  hypertension: "高血压/水肿：盐控制在每日不超过5g，少用酱菜、火腿、浓汤和高钠调味。",
  anemia: "贫血：优先瘦肉、牛肉、动物肝脏少量和深绿叶菜，搭配维生素C水果帮助铁吸收。",
  constipation: "便秘：增加熟蔬菜、全谷杂豆、水果和饮水，避免长期只喝汤不吃菜。",
  thyroid: "甲状腺问题：含碘海藻类不做默认推荐，具体碘摄入按复查和医嘱。",
  pluggedDuctRisk: "堵奶风险：避免高脂浓汤和短期大量催乳食材，优先规律排乳、补水和均衡蛋白。",
  lactoseIntolerance: "乳糖不耐：奶类优先选择无乳糖奶、酸奶或强化钙豆制品，观察腹胀腹泻。",
  diabetes: "糖尿病/血糖偏高：主食定量分配，优先全谷杂豆、蔬菜和优质蛋白，水果小份量并避免果汁。",
  hyperlipidemia: "血脂偏高：减少油炸、肥肉、奶油点心和浓汤，优先蒸煮炖拌及低脂蛋白。",
  goutHighUricAcid: "高尿酸/痛风：避免酒精、浓肉汤、动物内脏和大量高嘌呤海鲜，注意足量饮水。",
  kidneyDisease: "肾功能异常：蛋白、钠、钾、磷摄入需按医嘱个体化，本方案只给保守提醒。",
  osteoporosis: "骨质疏松/骨量低：重视奶豆、钙、维生素D和优质蛋白，配合安全日晒和抗阻活动。",
  dysphagia: "咀嚼/吞咽困难：食物需软烂、细碎、湿润，呛咳明显或吞咽障碍需先做专业评估。",
};
