import type { MedicalHistory, Recipe, RecoveryAction } from "./types";

export const defaultProfileOptions = {
  restrictions: [
    ["noPork", "不吃猪肉"],
    ["noBeefLamb", "不吃牛羊"],
    ["vegetarian", "素食"],
    ["noSeafood", "不吃海鲜"],
    ["noEgg", "鸡蛋过敏/不吃蛋"],
    ["noMilk", "不吃奶制品"],
    ["noSoy", "不吃大豆"],
    ["noPeanut", "不吃花生"],
  ],
  medicalHistory: [
    ["gestationalDiabetes", "妊娠糖尿病/血糖管理"],
    ["hypertension", "高血压/水肿"],
    ["anemia", "贫血/铁储备低"],
    ["constipation", "便秘"],
    ["thyroid", "甲状腺问题"],
    ["pluggedDuctRisk", "堵奶/乳腺胀痛风险"],
    ["lactoseIntolerance", "乳糖不耐受"],
  ],
  goals: [
    ["weightControl", "控制体重"],
    ["lactation", "促进泌乳"],
    ["iron", "补铁"],
    ["calcium", "补钙"],
    ["lightTaste", "清淡少盐"],
    ["constipationRelief", "改善便秘"],
    ["woundHealing", "伤口恢复"],
  ],
} as const;

export const phaseLabels = [
  { min: 1, max: 3, label: "第1-3天 清淡易消化" },
  { min: 4, max: 7, label: "第4-7天 增加蛋白与铁" },
  { min: 8, max: 14, label: "第8-14天 稳定泌乳" },
  { min: 15, max: 28, label: "第15-28天 控重与恢复并重" },
  { min: 29, max: 42, label: "第29-42天 长期哺乳期过渡" },
];

export const fruitPool = [
  "苹果150g，去皮蒸温或常温切块",
  "猕猴桃1个，常温食用，便秘者优先",
  "橙子150g，常温食用，补充维生素C帮助铁吸收",
  "香蕉半根到1根，血糖管理者改半根并随正餐吃",
  "蓝莓80g配无糖酸奶，乳糖不耐者改无糖豆乳",
  "雪梨150g，蒸温后食用，咽干者可选",
  "火龙果150g，便秘者可选，腹泻者避开",
];

export const nutritionPrinciples = [
  "每日覆盖谷薯、鱼禽蛋肉、奶豆、蔬菜、水果和少量坚果，不用单一大补。",
  "乳母参考：谷类225-275g、蔬菜400-500g、水果200-400g、鱼禽蛋肉175-225g、奶类300-500g、大豆25g、坚果10g、油25-30g、盐不超过5g。",
  "出奶优先保证足量能量、优质蛋白、液体和规律哺乳，避免酒酿、药膳滥用和油腻浓汤。",
  "妊娠糖尿病、高血压、贫血、甲状腺疾病等人群需遵医嘱复查，本工具只做饮食教育与保守建议。",
  "食品卫生坚持生熟分开、彻底加热、剩菜冷藏并充分复热，避免生食海鲜、未消毒奶制品和酒精饮品。",
];

export const recipes: Recipe[] = [
  {
    id: "b-rice-millet-egg",
    name: "小米南瓜粥配嫩蒸蛋",
    mealType: "breakfast",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["小米35g", "大米20g", "南瓜80g", "鸡蛋1个", "青菜碎30g"],
    seasonings: ["盐0.5g", "芝麻油2g"],
    steps: ["小米和大米淘洗后加水煮25分钟。", "南瓜切丁同煮至软烂。", "鸡蛋加1.5倍温水打匀，蒸8分钟。", "青菜碎焯熟后拌入粥中。"],
    nutritionTags: ["易消化", "优质蛋白", "β-胡萝卜素"],
    avoidTags: ["noEgg"],
    preferTags: ["woundHealing", "lightTaste"],
    replacements: ["鸡蛋过敏时改嫩豆腐80g或鸡胸肉丝40g。"],
    safetyNote: "鸡蛋蒸至完全凝固，不吃半熟蛋。",
  },
  {
    id: "b-oat-milk-berry",
    name: "燕麦牛奶粥配蓝莓核桃",
    mealType: "breakfast",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["燕麦40g", "低脂牛奶250ml", "蓝莓60g", "核桃仁8g", "奇亚籽3g"],
    seasonings: ["不加糖", "肉桂粉少量可选"],
    steps: ["燕麦加牛奶小火煮6分钟。", "关火焖3分钟至软糯。", "蓝莓洗净沥干，核桃掰碎。", "温热后加入蓝莓和核桃。"],
    nutritionTags: ["钙", "膳食纤维", "控重"],
    avoidTags: ["noMilk", "lactoseIntolerance", "noPeanut"],
    preferTags: ["calcium", "constipationRelief", "weightControl"],
    replacements: ["乳糖不耐者改无糖豆乳250ml；坚果过敏者去掉核桃。"],
    safetyNote: "奶类开封后冷藏，避免久放。",
  },
  {
    id: "b-chicken-noodle",
    name: "鸡丝青菜软汤面",
    mealType: "breakfast",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["细面60g", "鸡胸肉50g", "小白菜80g", "胡萝卜30g", "姜片2片"],
    seasonings: ["盐1g", "低盐酱油3ml"],
    steps: ["鸡胸肉煮熟撕丝。", "面条煮至软烂。", "小白菜和胡萝卜烫熟。", "用鸡汤撇油后煮面，最后加鸡丝和蔬菜。"],
    nutritionTags: ["优质蛋白", "补液", "清淡"],
    avoidTags: [],
    preferTags: ["lactation", "woundHealing"],
    replacements: ["不吃禽肉者改豆腐100g或瘦牛肉40g。"],
    safetyNote: "鸡汤需撇去浮油，不用隔夜常温汤。",
  },
  {
    id: "b-redbean-rice",
    name: "红豆糙米软饭配香菇青菜",
    mealType: "breakfast",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["糙米40g", "大米30g", "红豆20g", "香菇30g", "油菜100g"],
    seasonings: ["盐1g", "菜籽油5g"],
    steps: ["红豆提前浸泡并煮软。", "糙米和大米同煮成软饭。", "香菇切片和油菜快炒至熟。", "把红豆拌入软饭搭配蔬菜。"],
    nutritionTags: ["全谷杂豆", "膳食纤维", "控糖友好"],
    avoidTags: [],
    preferTags: ["gestationalDiabetes", "constipationRelief", "weightControl"],
    replacements: ["胀气明显时红豆减半，改山药80g。"],
    safetyNote: "杂豆需煮透，避免夹生引起胃肠不适。",
  },
  {
    id: "b-shrimp-wonton",
    name: "虾仁青菜小馄饨",
    mealType: "breakfast",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["馄饨皮50g", "虾仁60g", "鸡蛋半个", "小白菜90g", "紫菜1g"],
    seasonings: ["盐1g", "白胡椒少量", "芝麻油2g"],
    steps: ["虾仁剁泥后与鸡蛋拌匀。", "包成小馄饨。", "水开后煮至浮起再煮2分钟。", "加入小白菜和紫菜。"],
    nutritionTags: ["优质蛋白", "碘", "低脂"],
    avoidTags: ["noSeafood", "noEgg"],
    preferTags: ["lactation", "weightControl"],
    replacements: ["海鲜过敏时改鸡肉馄饨；鸡蛋过敏时去蛋加少量山药泥。"],
    safetyNote: "虾仁必须煮熟，避免生食或半熟。",
  },
  {
    id: "b-tofu-congee",
    name: "山药豆腐瘦肉粥",
    mealType: "breakfast",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["大米50g", "山药80g", "北豆腐80g", "瘦猪肉35g", "生菜50g"],
    seasonings: ["盐1g", "姜丝2g"],
    steps: ["大米煮成绵粥。", "山药切小块同煮。", "瘦肉剁末焯水后加入。", "豆腐切丁煮透，最后放生菜。"],
    nutritionTags: ["蛋白质", "钙", "易消化"],
    avoidTags: ["noPork", "noSoy"],
    preferTags: ["calcium", "woundHealing"],
    replacements: ["不吃猪肉改鸡腿肉40g；不吃豆制品改鸡蛋1个。"],
    safetyNote: "山药去皮时注意手部防痒，豆腐充分加热。",
  },
  {
    id: "l-steamed-cod",
    name: "清蒸鳕鱼配番茄豆腐青菜饭",
    mealType: "lunch",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["鳕鱼100g", "番茄120g", "北豆腐100g", "西兰花120g", "米饭120g"],
    seasonings: ["姜丝3g", "葱花3g", "低盐酱油5ml", "菜籽油6g"],
    steps: ["鳕鱼加姜丝蒸8-10分钟。", "番茄和豆腐煮成清汤。", "西兰花焯熟后少油快炒。", "搭配温热米饭食用。"],
    nutritionTags: ["DHA", "钙", "低脂蛋白"],
    avoidTags: ["noSeafood", "noSoy"],
    preferTags: ["lactation", "calcium", "weightControl"],
    replacements: ["海鲜过敏改清蒸鸡腿肉100g；不吃豆腐改鸡蛋羹1份。"],
    safetyNote: "鱼肉蒸至中心完全变白，选择低汞鱼类。",
  },
  {
    id: "l-chicken-lotus",
    name: "莲藕鸡腿肉焖饭配菠菜",
    mealType: "lunch",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["去皮鸡腿肉110g", "莲藕90g", "胡萝卜50g", "大米80g", "菠菜120g"],
    seasonings: ["姜片3g", "低盐酱油6ml", "盐1g", "菜籽油6g"],
    steps: ["鸡腿肉切块焯水。", "莲藕和胡萝卜切丁。", "食材与大米同焖至熟。", "菠菜焯水后少油拌炒。"],
    nutritionTags: ["优质蛋白", "铁", "维生素C"],
    avoidTags: [],
    preferTags: ["iron", "woundHealing", "anemia"],
    replacements: ["不吃鸡肉者改瘦牛肉90g或豆腐150g。"],
    safetyNote: "禽肉焖熟到无血水，菠菜焯水减少草酸。",
  },
  {
    id: "l-beef-tomato",
    name: "番茄牛肉土豆炖菜配杂粮饭",
    mealType: "lunch",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["瘦牛肉90g", "番茄180g", "土豆80g", "洋葱30g", "杂粮饭120g"],
    seasonings: ["姜片2g", "盐1g", "低盐酱油5ml"],
    steps: ["牛肉切小块焯水。", "番茄炒出汁后加牛肉慢炖。", "加入土豆炖软。", "搭配杂粮饭，血糖管理者土豆减半。"],
    nutritionTags: ["血红素铁", "蛋白质", "控糖替换"],
    avoidTags: ["noBeefLamb"],
    preferTags: ["anemia", "iron"],
    replacements: ["不吃牛肉改瘦猪肉90g或鸡肉100g。"],
    safetyNote: "牛肉充分炖熟，剩余炖菜冷藏并彻底复热。",
  },
  {
    id: "l-pork-liver",
    name: "猪肝瘦肉菠菜汤饭",
    mealType: "lunch",
    phaseMin: 8,
    phaseMax: 28,
    ingredients: ["猪肝40g", "瘦猪肉50g", "菠菜120g", "大米饭120g", "枸杞3g"],
    seasonings: ["姜丝3g", "盐1g", "白胡椒少量"],
    steps: ["猪肝切薄片反复冲洗并焯水。", "瘦肉煮汤后撇沫。", "加入猪肝煮至全熟。", "菠菜焯水后入汤，配米饭。"],
    nutritionTags: ["补铁", "叶酸", "蛋白质"],
    avoidTags: ["noPork", "hypertension"],
    preferTags: ["anemia", "iron"],
    replacements: ["不吃猪肉改牛肉80g加菠菜；高血压者改鸡肉菠菜汤。"],
    safetyNote: "动物肝脏每周1-2次即可，必须彻底煮熟。",
  },
  {
    id: "l-tofu-mushroom",
    name: "香菇豆腐鸡蛋羹配荞麦饭",
    mealType: "lunch",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["北豆腐150g", "鸡蛋1个", "香菇60g", "油麦菜120g", "荞麦饭120g"],
    seasonings: ["盐1g", "低盐酱油4ml", "芝麻油2g"],
    steps: ["鸡蛋加温水打匀。", "豆腐切丁和香菇片放入蛋液。", "蒸12分钟至凝固。", "油麦菜清炒后配荞麦饭。"],
    nutritionTags: ["钙", "植物蛋白", "控糖友好"],
    avoidTags: ["noSoy", "noEgg"],
    preferTags: ["gestationalDiabetes", "calcium", "weightControl"],
    replacements: ["不吃豆制品改鸡肉末80g；不吃蛋改豆腐蒸肉末。"],
    safetyNote: "蛋羹中心凝固后再食用。",
  },
  {
    id: "l-vegetarian-bowl",
    name: "三色豆腐杂粮能量碗",
    mealType: "lunch",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["北豆腐180g", "鹰嘴豆50g", "藜麦饭120g", "西兰花120g", "彩椒60g"],
    seasonings: ["盐1g", "橄榄油6g", "醋5ml", "低盐酱油4ml"],
    steps: ["鹰嘴豆提前煮熟。", "豆腐煎至两面微黄。", "西兰花和彩椒焯熟。", "与藜麦饭组合，少量油醋调味。"],
    nutritionTags: ["素食蛋白", "膳食纤维", "控重"],
    avoidTags: ["noSoy"],
    preferTags: ["vegetarian", "constipationRelief", "weightControl"],
    replacements: ["不吃豆制品时素食版需营养师补充蛋白方案。"],
    safetyNote: "杂豆提前浸泡并煮透。",
  },
  {
    id: "d-salmon-rice",
    name: "三文鱼南瓜饭配芦笋",
    mealType: "dinner",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["三文鱼90g", "南瓜100g", "大米70g", "芦笋120g", "海带芽5g"],
    seasonings: ["柠檬汁3ml", "盐1g", "姜片2g", "菜籽油5g"],
    steps: ["三文鱼加姜片蒸熟。", "南瓜和大米同焖。", "芦笋焯水后少油快炒。", "海带芽煮汤，不额外加盐。"],
    nutritionTags: ["DHA", "碘", "高营养密度"],
    avoidTags: ["noSeafood", "thyroid"],
    preferTags: ["lactation", "weightControl"],
    replacements: ["海鲜过敏改鸡胸肉100g；甲状腺问题者去海带芽并遵医嘱控碘。"],
    safetyNote: "三文鱼必须全熟，避免刺身。",
  },
  {
    id: "d-turkey-veg",
    name: "鸡胸肉山药时蔬盘",
    mealType: "dinner",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["鸡胸肉100g", "山药100g", "胡萝卜60g", "西葫芦120g", "小米饭100g"],
    seasonings: ["姜汁2ml", "盐1g", "低盐酱油4ml", "菜籽油6g"],
    steps: ["鸡胸肉切片用姜汁抓匀。", "山药蒸熟。", "胡萝卜和西葫芦炒熟。", "鸡肉煎焖至全熟，配小米饭。"],
    nutritionTags: ["低脂蛋白", "控重", "伤口恢复"],
    avoidTags: [],
    preferTags: ["weightControl", "woundHealing"],
    replacements: ["不吃鸡肉改鱼肉或豆腐。"],
    safetyNote: "鸡肉中心无粉色再出锅。",
  },
  {
    id: "d-pork-tenderloin",
    name: "里脊肉冬瓜木耳汤配软饭",
    mealType: "dinner",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["猪里脊80g", "冬瓜180g", "黑木耳50g", "大米饭110g", "小白菜80g"],
    seasonings: ["姜片3g", "盐1g", "白胡椒少量"],
    steps: ["里脊切片焯水。", "冬瓜煮软后加入里脊。", "木耳充分泡发洗净后煮透。", "配软饭和小白菜。"],
    nutritionTags: ["清淡", "补液", "低脂"],
    avoidTags: ["noPork"],
    preferTags: ["lightTaste", "hypertension", "woundHealing"],
    replacements: ["不吃猪肉改鸡腿肉90g。"],
    safetyNote: "干木耳泡发后及时烹调，不隔夜浸泡。",
  },
  {
    id: "d-eggplant-chicken",
    name: "番茄茄子鸡肉煲配燕麦饭",
    mealType: "dinner",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["鸡腿肉90g", "番茄160g", "茄子120g", "燕麦饭110g", "香菇40g"],
    seasonings: ["蒜末2g", "盐1g", "低盐酱油5ml", "菜籽油6g"],
    steps: ["茄子切块蒸软减少吸油。", "鸡腿肉焯水。", "番茄炒出汁后加入鸡肉和茄子焖熟。", "搭配燕麦饭。"],
    nutritionTags: ["控油", "优质蛋白", "全谷"],
    avoidTags: [],
    preferTags: ["weightControl", "constipationRelief"],
    replacements: ["不吃鸡肉改瘦肉或豆腐。"],
    safetyNote: "不用油炸茄子，控制总油量。",
  },
  {
    id: "d-shrimp-tofu",
    name: "虾仁豆腐蒸蛋配青菜",
    mealType: "dinner",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["虾仁70g", "嫩豆腐120g", "鸡蛋1个", "青菜150g", "米饭100g"],
    seasonings: ["盐1g", "低盐酱油4ml", "芝麻油2g"],
    steps: ["鸡蛋加温水打匀。", "豆腐和虾仁铺入碗中。", "蒸12分钟至虾仁变色且蛋液凝固。", "青菜焯熟，配米饭。"],
    nutritionTags: ["蛋白质", "钙", "低脂"],
    avoidTags: ["noSeafood", "noSoy", "noEgg"],
    preferTags: ["calcium", "lactation"],
    replacements: ["海鲜过敏改鸡肉末；不吃蛋改清蒸豆腐鸡肉。"],
    safetyNote: "虾仁和鸡蛋都要完全熟透。",
  },
  {
    id: "d-veg-millet",
    name: "菌菇青菜小米豆腐煲",
    mealType: "dinner",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["小米饭100g", "北豆腐150g", "口蘑80g", "油菜150g", "胡萝卜50g"],
    seasonings: ["盐1g", "菜籽油5g", "姜丝2g"],
    steps: ["小米饭提前煮软。", "豆腐切块煮透。", "口蘑和胡萝卜煮熟。", "加入油菜，少油少盐调味。"],
    nutritionTags: ["素食", "钙", "清淡"],
    avoidTags: ["noSoy"],
    preferTags: ["vegetarian", "lightTaste", "calcium"],
    replacements: ["不吃豆制品改鸡蛋或鱼肉；严格素食需补充B12咨询。"],
    safetyNote: "菌菇类必须煮熟。",
  },
  {
    id: "s-crucian-tofu",
    name: "鲫鱼豆腐清汤",
    mealType: "soup",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["鲫鱼120g", "北豆腐100g", "姜片4g", "小葱3g", "清水600ml"],
    seasonings: ["盐1g", "白胡椒少量"],
    steps: ["鲫鱼处理干净后煎至表面定型。", "加热水和姜片煮20分钟。", "撇去浮油后加豆腐。", "出锅少量盐调味。"],
    nutritionTags: ["补液", "优质蛋白", "泌乳支持"],
    avoidTags: ["noSeafood", "noSoy", "pluggedDuctRisk"],
    preferTags: ["lactation"],
    replacements: ["海鲜过敏改鸡丝豆腐汤；堵奶明显时改冬瓜鸡汤并减少脂肪。"],
    safetyNote: "鱼刺仔细剔除，汤不需熬到浓白油厚。",
  },
  {
    id: "s-chicken-corn",
    name: "玉米胡萝卜去皮鸡汤",
    mealType: "soup",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["去皮鸡腿肉90g", "玉米80g", "胡萝卜80g", "姜片3g", "清水600ml"],
    seasonings: ["盐1g"],
    steps: ["鸡腿肉焯水去浮沫。", "加入玉米、胡萝卜和姜片。", "小火煮30分钟。", "冷却片刻撇油后饮用。"],
    nutritionTags: ["补液", "清淡蛋白", "能量"],
    avoidTags: [],
    preferTags: ["lactation", "woundHealing"],
    replacements: ["不吃鸡肉改瘦肉冬瓜汤或豆腐菌菇汤。"],
    safetyNote: "汤面浮油撇去，不喝油汤。",
  },
  {
    id: "s-wintermelon-pork",
    name: "冬瓜海带瘦肉汤",
    mealType: "soup",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["冬瓜200g", "瘦猪肉60g", "海带结20g", "姜片3g", "清水600ml"],
    seasonings: ["盐1g"],
    steps: ["瘦肉焯水。", "冬瓜切片。", "海带充分清洗后同煮。", "煮至冬瓜透明，少盐调味。"],
    nutritionTags: ["补液", "低脂", "碘"],
    avoidTags: ["noPork", "thyroid"],
    preferTags: ["hypertension", "weightControl"],
    replacements: ["不吃猪肉改鸡肉；甲状腺问题者去海带改香菇。"],
    safetyNote: "甲状腺疾病按医生建议控制碘摄入。",
  },
  {
    id: "s-redbean-barley",
    name: "红豆山药汤",
    mealType: "soup",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["红豆25g", "山药80g", "红枣1枚", "清水600ml"],
    seasonings: ["不加糖"],
    steps: ["红豆提前浸泡。", "加水煮至开花。", "加入山药煮软。", "红枣只放1枚提味，不额外加糖。"],
    nutritionTags: ["膳食纤维", "补液", "控糖调整"],
    avoidTags: [],
    preferTags: ["constipationRelief", "weightControl"],
    replacements: ["血糖管理者红枣可不放，红豆减为15g。"],
    safetyNote: "杂豆煮透，腹胀明显者减少用量。",
  },
  {
    id: "s-mushroom-tofu",
    name: "菌菇豆腐青菜汤",
    mealType: "soup",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["嫩豆腐120g", "口蘑80g", "小白菜100g", "姜丝2g", "清水600ml"],
    seasonings: ["盐1g", "芝麻油1g"],
    steps: ["口蘑切片煮透。", "加入豆腐煮5分钟。", "小白菜最后放入。", "少盐和少量芝麻油调味。"],
    nutritionTags: ["清淡", "钙", "补液"],
    avoidTags: ["noSoy"],
    preferTags: ["lightTaste", "calcium", "vegetarian"],
    replacements: ["不吃豆制品改鸡蛋花或鸡丝。"],
    safetyNote: "菌菇彻底加热，不吃未熟菌菇。",
  },
  {
    id: "sn-yogurt-oat",
    name: "无糖酸奶燕麦杯",
    mealType: "snack",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["无糖酸奶180g", "即食燕麦15g", "蓝莓40g"],
    seasonings: ["不加糖"],
    steps: ["酸奶保持冷藏。", "食用前加入燕麦。", "蓝莓洗净沥干后加入。"],
    nutritionTags: ["钙", "益生菌", "膳食纤维"],
    avoidTags: ["noMilk", "lactoseIntolerance"],
    preferTags: ["calcium", "constipationRelief"],
    replacements: ["乳糖不耐改无糖豆乳200ml加燕麦。"],
    safetyNote: "酸奶离开冷藏不超过2小时。",
  },
  {
    id: "sn-egg-sweetpotato",
    name: "蒸红薯配水煮蛋",
    mealType: "snack",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["红薯120g", "鸡蛋1个"],
    seasonings: ["不加盐"],
    steps: ["红薯洗净蒸熟。", "鸡蛋冷水下锅煮10分钟。", "分成下午加餐或夜间轻食。"],
    nutritionTags: ["饱腹", "优质蛋白", "钾"],
    avoidTags: ["noEgg"],
    preferTags: ["weightControl", "lactation"],
    replacements: ["鸡蛋过敏改豆腐干40g或鸡胸肉40g。"],
    safetyNote: "鸡蛋全熟，红薯血糖管理者减半。",
  },
  {
    id: "sn-soymilk-nut",
    name: "无糖豆浆配坚果",
    mealType: "snack",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["无糖豆浆250ml", "巴旦木10g", "全麦馒头半个"],
    seasonings: ["不加糖"],
    steps: ["豆浆煮沸后再小火3分钟。", "坚果称量10g。", "搭配半个全麦馒头避免空腹饥饿。"],
    nutritionTags: ["植物蛋白", "钙", "控重"],
    avoidTags: ["noSoy", "noPeanut"],
    preferTags: ["lactation", "calcium", "weightControl"],
    replacements: ["不吃豆制品改低脂奶；坚果过敏去掉坚果。"],
    safetyNote: "豆浆必须煮透，避免生豆浆。",
  },
  {
    id: "sn-pear-millet",
    name: "蒸梨小米饮",
    mealType: "snack",
    phaseMin: 1,
    phaseMax: 42,
    ingredients: ["雪梨150g", "小米15g", "清水400ml"],
    seasonings: ["不加冰糖"],
    steps: ["小米煮成稀饮。", "雪梨去核切块蒸10分钟。", "温热搭配食用。"],
    nutritionTags: ["补液", "温和水果", "少糖"],
    avoidTags: [],
    preferTags: ["lightTaste", "lactation"],
    replacements: ["血糖管理者梨减为80g并随正餐吃。"],
    safetyNote: "不加冰糖，避免把水果饮做成甜汤。",
  },
  {
    id: "sn-chicken-toast",
    name: "鸡丝全麦小三明治",
    mealType: "snack",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["全麦吐司1片", "熟鸡胸肉40g", "生菜30g", "番茄40g"],
    seasonings: ["低脂酸奶酱10g", "黑胡椒少量"],
    steps: ["鸡胸肉煮熟撕丝。", "生菜和番茄洗净沥干。", "夹入吐司，少量酸奶酱调味。"],
    nutritionTags: ["蛋白质", "控重", "全谷"],
    avoidTags: ["noMilk"],
    preferTags: ["weightControl", "lactation"],
    replacements: ["不吃奶制品改牛油果泥10g或不加酱。"],
    safetyNote: "熟鸡肉冷藏保存，当天食用。",
  },
  {
    id: "b-black-sesame-yam",
    name: "黑芝麻山药米糊配鸡肉松",
    mealType: "breakfast",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["大米35g", "山药80g", "熟黑芝麻6g", "鸡胸肉松35g", "小白菜60g"],
    seasonings: ["盐0.5g", "不加糖"],
    steps: ["大米和山药煮软后打成细米糊。", "熟黑芝麻研碎后拌入。", "鸡胸肉煮熟撕细后少盐烘干成肉松。", "小白菜焯熟切碎搭配食用。"],
    nutritionTags: ["钙", "易消化", "优质蛋白"],
    avoidTags: [],
    preferTags: ["calcium", "lactation", "woundHealing"],
    replacements: ["不吃鸡肉者改鱼肉松或豆腐碎；血糖管理者山药减半。"],
    safetyNote: "黑芝麻需熟制，肉松当天制作或冷藏保存。",
  },
  {
    id: "b-spinach-egg-roll",
    name: "菠菜鸡蛋软卷配番茄粥",
    mealType: "breakfast",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["鸡蛋1个", "菠菜80g", "面粉35g", "番茄120g", "大米35g"],
    seasonings: ["盐1g", "菜籽油4g"],
    steps: ["大米和番茄煮成软粥。", "菠菜焯水切碎。", "鸡蛋、面粉和菠菜拌成稀糊。", "平底锅少油摊成软卷。"],
    nutritionTags: ["铁", "叶酸", "软食"],
    avoidTags: ["noEgg"],
    preferTags: ["anemia", "iron", "woundHealing"],
    replacements: ["鸡蛋过敏者改豆腐蔬菜饼；不吃面粉者改米粉。"],
    safetyNote: "菠菜先焯水，蛋卷完全熟透。",
  },
  {
    id: "l-shrimp-pea-rice",
    name: "虾仁豌豆滑蛋饭",
    mealType: "lunch",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["虾仁80g", "鸡蛋1个", "豌豆50g", "胡萝卜50g", "米饭120g"],
    seasonings: ["姜末2g", "盐1g", "菜籽油6g"],
    steps: ["虾仁去虾线后焯至变色。", "豌豆和胡萝卜煮熟。", "鸡蛋炒至凝固后加入虾仁和蔬菜。", "搭配米饭，少油完成。"],
    nutritionTags: ["优质蛋白", "低脂", "锌"],
    avoidTags: ["noSeafood", "noEgg"],
    preferTags: ["lactation", "weightControl"],
    replacements: ["海鲜过敏改鸡丁；鸡蛋过敏改嫩豆腐。"],
    safetyNote: "虾仁必须全熟，豌豆煮透。",
  },
  {
    id: "l-pork-pumpkin-quinoa",
    name: "南瓜瘦肉藜麦饭",
    mealType: "lunch",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["瘦猪肉90g", "南瓜100g", "藜麦饭120g", "芥蓝120g", "香菇40g"],
    seasonings: ["姜丝3g", "低盐酱油5ml", "盐1g", "菜籽油6g"],
    steps: ["瘦肉切片焯水后快炒。", "南瓜蒸熟压块。", "芥蓝焯水后与香菇少油炒熟。", "搭配藜麦饭组合成餐盘。"],
    nutritionTags: ["全谷", "优质蛋白", "控重"],
    avoidTags: ["noPork"],
    preferTags: ["weightControl", "constipationRelief"],
    replacements: ["不吃猪肉改鸡胸肉或鱼肉；血糖管理者南瓜减半。"],
    safetyNote: "瘦肉炒熟到无粉色，熟饭当天食用。",
  },
  {
    id: "d-duck-mushroom-rice",
    name: "去皮鸭肉菌菇软饭",
    mealType: "dinner",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["去皮鸭胸肉80g", "口蘑80g", "杏鲍菇60g", "油菜140g", "软米饭110g"],
    seasonings: ["姜片3g", "盐1g", "低盐酱油4ml"],
    steps: ["鸭胸去皮切薄片并焯水。", "菌菇切片煮透。", "鸭肉和菌菇小火焖熟。", "油菜焯熟后搭配软饭。"],
    nutritionTags: ["铁", "蛋白质", "控油"],
    avoidTags: [],
    preferTags: ["anemia", "weightControl"],
    replacements: ["不吃鸭肉改鸡腿肉或瘦牛肉。"],
    safetyNote: "鸭皮脂肪高，建议去皮并撇油。",
  },
  {
    id: "d-cod-millet-pumpkin",
    name: "鳕鱼小米南瓜煲",
    mealType: "dinner",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["鳕鱼90g", "小米50g", "南瓜80g", "西葫芦120g", "姜片2g"],
    seasonings: ["盐1g", "葱花3g"],
    steps: ["小米和南瓜煮成软煲。", "鳕鱼切块加姜片蒸熟。", "西葫芦切片煮熟。", "鱼肉去刺后放入小米煲中。"],
    nutritionTags: ["DHA", "易消化", "低脂"],
    avoidTags: ["noSeafood"],
    preferTags: ["lactation", "lightTaste", "weightControl"],
    replacements: ["海鲜过敏改鸡胸肉或嫩豆腐。"],
    safetyNote: "鱼刺仔细剔除，鱼肉彻底加热。",
  },
  {
    id: "s-tomato-beef-clear",
    name: "番茄牛肉清汤",
    mealType: "soup",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["瘦牛肉70g", "番茄180g", "芹菜30g", "姜片3g", "清水600ml"],
    seasonings: ["盐1g", "白胡椒少量"],
    steps: ["牛肉焯水后切小块。", "番茄煮出汤汁。", "加入牛肉和姜片小火煮25分钟。", "最后放芹菜增香。"],
    nutritionTags: ["补铁", "补液", "低脂"],
    avoidTags: ["noBeefLamb"],
    preferTags: ["anemia", "iron", "lightTaste"],
    replacements: ["不吃牛肉改鸡肉番茄汤。"],
    safetyNote: "汤面浮油撇去，高血压者不额外加酱油。",
  },
  {
    id: "s-loofah-egg",
    name: "丝瓜鸡蛋清汤",
    mealType: "soup",
    phaseMin: 4,
    phaseMax: 42,
    ingredients: ["丝瓜180g", "鸡蛋1个", "姜丝2g", "清水550ml"],
    seasonings: ["盐1g", "芝麻油1g"],
    steps: ["丝瓜去皮切片。", "清水加姜丝煮开后放丝瓜。", "鸡蛋打散后淋入成蛋花。", "少盐和少量芝麻油调味。"],
    nutritionTags: ["清淡", "补液", "优质蛋白"],
    avoidTags: ["noEgg"],
    preferTags: ["lactation", "lightTaste"],
    replacements: ["鸡蛋过敏改嫩豆腐80g。"],
    safetyNote: "蛋花完全凝固后食用。",
  },
  {
    id: "sn-snow-fungus-pear",
    name: "银耳雪梨低糖羹",
    mealType: "snack",
    phaseMin: 8,
    phaseMax: 42,
    ingredients: ["干银耳4g", "雪梨100g", "枸杞3g", "清水450ml"],
    seasonings: ["不加糖"],
    steps: ["银耳泡发后去蒂撕小朵。", "加水煮至软糯。", "加入雪梨块再煮8分钟。", "出锅前放枸杞。"],
    nutritionTags: ["甜品", "补液", "少糖"],
    avoidTags: [],
    preferTags: ["lightTaste", "constipationRelief"],
    replacements: ["血糖管理者雪梨减为60g并随正餐吃。"],
    safetyNote: "银耳泡发后当天烹调，不隔夜浸泡。",
  },
  {
    id: "sn-purple-yam-dessert",
    name: "紫薯山药酸奶杯",
    mealType: "snack",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["紫薯70g", "山药70g", "无糖酸奶120g", "蓝莓30g"],
    seasonings: ["不加糖"],
    steps: ["紫薯和山药蒸熟后压成小块。", "放至温热。", "加入无糖酸奶和蓝莓。", "搅拌后作为下午甜品加餐。"],
    nutritionTags: ["甜品", "钙", "膳食纤维"],
    avoidTags: ["noMilk", "lactoseIntolerance"],
    preferTags: ["calcium", "constipationRelief", "weightControl"],
    replacements: ["乳糖不耐改无糖豆乳酸奶；血糖管理者紫薯减半。"],
    safetyNote: "酸奶冷藏保存，取出后尽快食用。",
  },
  {
    id: "sn-pumpkin-milk-pudding",
    name: "南瓜牛奶蒸布丁",
    mealType: "snack",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["南瓜100g", "鸡蛋1个", "低脂牛奶120ml"],
    seasonings: ["不加糖", "肉桂粉少量可选"],
    steps: ["南瓜蒸熟压泥。", "鸡蛋和牛奶打匀后过滤。", "加入南瓜泥拌匀。", "盖盘蒸12-15分钟至凝固。"],
    nutritionTags: ["甜品", "优质蛋白", "钙"],
    avoidTags: ["noEgg", "noMilk", "lactoseIntolerance"],
    preferTags: ["calcium", "woundHealing"],
    replacements: ["乳糖不耐改无糖豆乳；鸡蛋过敏者改山药南瓜泥。"],
    safetyNote: "布丁中心完全凝固，不吃半熟蛋奶制品。",
  },
  {
    id: "sn-red-date-oat-cake",
    name: "红枣燕麦蒸糕",
    mealType: "snack",
    phaseMin: 15,
    phaseMax: 42,
    ingredients: ["燕麦粉35g", "鸡蛋1个", "红枣1枚", "无糖豆浆60ml"],
    seasonings: ["不加糖"],
    steps: ["红枣去核切碎。", "燕麦粉、鸡蛋和豆浆拌匀。", "加入红枣碎。", "模具蒸15分钟至熟透。"],
    nutritionTags: ["甜品", "全谷", "饱腹"],
    avoidTags: ["noEgg", "noSoy"],
    preferTags: ["weightControl", "constipationRelief"],
    replacements: ["血糖管理者去红枣；不吃蛋改香蕉泥少量但需减少主食。"],
    safetyNote: "红枣只用1枚提味，不额外加糖。",
  },
];

export const recoveryBaseActions: Record<string, RecoveryAction> = {
  breathing: {
    name: "腹式呼吸",
    duration: "5分钟",
    steps: ["仰卧或侧卧，双手放在下肋。", "吸气时肋骨向两侧打开，呼气时轻收下腹。", "全程不憋气，不追求用力收腹。"],
    suitableFor: ["顺产", "剖宫产", "产后早期"],
    avoidWhen: ["头晕", "胸闷", "伤口明显牵拉痛"],
  },
  pelvicFloor: {
    name: "盆底肌温和收缩",
    duration: "8-10次/组，2-3组",
    steps: ["像轻轻忍住排气一样向上收。", "保持2-3秒后完全放松。", "不要夹臀、憋气或用大腿代偿。"],
    suitableFor: ["顺产", "剖宫产", "尿失禁预防"],
    avoidWhen: ["会阴疼痛加重", "盆底痉挛感", "恶露明显增多"],
  },
  anklePump: {
    name: "踝泵",
    duration: "每侧20次",
    steps: ["平躺或坐位，脚尖向上勾。", "再缓慢向下绷脚。", "配合脚踝画圈促进循环。"],
    suitableFor: ["卧床多", "剖宫产早期"],
    avoidWhen: ["小腿单侧红肿热痛"],
  },
  shoulderNeck: {
    name: "肩颈放松",
    duration: "6分钟",
    steps: ["肩膀向后绕环10次。", "下巴微收做颈后侧拉长。", "哺乳后做胸前轻柔打开。"],
    suitableFor: ["哺乳", "抱娃肩颈紧"],
    avoidWhen: ["手臂麻木加重", "眩晕"],
  },
  pelvicTilt: {
    name: "骨盆前后倾",
    duration: "10次/组，2组",
    steps: ["仰卧屈膝或站姿扶墙。", "呼气时轻轻让腰背贴近床面。", "吸气还原，动作幅度小。"],
    suitableFor: ["产后腰背酸", "腹直肌恢复早期"],
    avoidWhen: ["剖宫产伤口牵拉痛", "出血增多"],
  },
  catCow: {
    name: "猫牛式",
    duration: "8-10次",
    steps: ["四点跪位，手在肩下、膝在髋下。", "吸气胸口打开，呼气背部轻柔拱起。", "保持慢速，不塌腰。"],
    suitableFor: ["第8天后恢复良好者"],
    avoidWhen: ["腕痛", "剖宫产伤口不适", "会阴疼痛加重"],
  },
  walk: {
    name: "轻松散步",
    duration: "10-30分钟",
    steps: ["从室内短距离开始。", "能说完整句子的强度即可。", "分2次完成也可以。"],
    suitableFor: ["恢复稳定", "控重", "情绪调节"],
    avoidWhen: ["头晕", "胸痛", "出血增多", "伤口疼痛"],
  },
  lightStrength: {
    name: "坐姿弹力带划船",
    duration: "10次/组，2组",
    steps: ["坐稳，弹力带绕脚或固定点。", "呼气时手肘向后拉。", "吸气慢慢还原，肩膀放松。"],
    suitableFor: ["第29天后恢复良好者", "肩背无痛"],
    avoidWhen: ["剖宫产伤口痛", "盆底下坠感", "尿失禁加重"],
  },
};

export const conditionNotes: Record<MedicalHistory, string> = {
  gestationalDiabetes: "血糖管理：主食分配到三餐两加餐，水果随正餐或加餐少量吃，避免甜汤、果汁和大量精制点心。",
  hypertension: "高血压/水肿：盐控制在每日不超过5g，少用酱菜、火腿、浓汤和高钠调味。",
  anemia: "贫血：优先瘦肉、牛肉、动物肝脏少量和深绿叶菜，搭配维生素C水果帮助铁吸收。",
  constipation: "便秘：增加熟蔬菜、全谷杂豆、水果和饮水，避免长期只喝汤不吃菜。",
  thyroid: "甲状腺问题：含碘海藻类不做默认推荐，具体碘摄入按复查和医嘱。",
  pluggedDuctRisk: "堵奶风险：避免高脂浓汤和短期大量催乳食材，优先规律排乳、补水和均衡蛋白。",
  lactoseIntolerance: "乳糖不耐：奶类优先选择无乳糖奶、酸奶或强化钙豆制品，观察腹胀腹泻。",
};
